
export const EMPLOYEE_ROLE_COLUMN_HEADER = {
  srno: {
    id: '0',
    fieldName: 'srno',
    colDisplayName: 'Sr No',
    colType: 'text',
    userIndex: 0,
    imgName: '',
    tooltipSrc: '',
    dataType: 'text',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 50,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  erRoleName: {
    userIndex: 1,
    fieldName: 'erRoleName',
    colDisplayName: 'Employee Role Name',
    title: 'Employee Role Name',
    widthOfColumn: 150,
    colType: 'textwithlink',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: 'openEmployeeRoleDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  // erIsPredifined: {
  //   userIndex: 2,
  //   fieldName: 'erIsPredifined',
  //   colDisplayName: 'Is Predefined',
  //   title: 'Is Predefined',
  //   widthOfColumn: 150,
  //   colType: 'text',
  //   dataType: 'text',
  //   id: '2',
  //   imgName: '',
  //   tooltipSrc: '',
  //   function: '',
  //   funParams: '',
  //   wrapData: '',
  //   isSortSupported: false,
  //   isCustomAttributeColumn: false
  // },
  empRoleCatID: {
    userIndex: 3,
    fieldName: 'empRoleCatID',
    colDisplayName: 'Role Category Id',
    title: 'Role Category Id',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  // erIsEscalationReq: {
  //   userIndex: 4,
  //   fieldName: 'erIsEscalationReq',
  //   colDisplayName: 'Is Escalation Request',
  //   title: 'Is Escalation Request',
  //   widthOfColumn: 150,
  //   colType: 'text',
  //   dataType: 'text',
  //   id: '4',
  //   imgName: '',
  //   tooltipSrc: '',
  //   function: '',
  //   funParams: '',
  //   wrapData: '',
  //   isSortSupported: false,
  //   isCustomAttributeColumn: false
  // },
  // erCategoryId: {
  //   userIndex: 5,
  //   fieldName: 'erCategoryId',
  //   colDisplayName: 'Category Id',
  //   title: 'Category Id',
  //   widthOfColumn: 150,
  //   colType: 'text',
  //   dataType: 'text',
  //   id: '5',
  //   imgName: '',
  //   tooltipSrc: '',
  //   function: '',
  //   funParams: '',
  //   wrapData: '',
  //   isSortSupported: false,
  //   isCustomAttributeColumn: false
  // },
  delete: {
    id: '5',
    fieldName: 'delete',
    colDisplayName: 'Action',
    colType: 'textwithlink',
    dataType: 'text',
    userIndex: 5,
    imgName: '',
    tooltipSrc: '',
    function: 'openEmployeeRoleDataForDelete',
    funParams: '',
    wrapData: '',
    widthOfColumn: 75,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
};
