
export const USERS_COLUMN_HEADER = {
  srno: {
    userIndex: 0,
    fieldName: 'srno',
    colDisplayName: 'SrNo',
    title: 'SrNo',
    widthOfColumn: 50,
    colType: 'text',
    dataType: 'text',
    id: '0',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  umName: {
    userIndex: 1,
    fieldName: 'umName',
    colDisplayName: 'Name',
    title: 'Site ID',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  username: {
    userIndex: 2,
    fieldName: 'username',
    colDisplayName: 'User name',
    title: 'User name',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  umEmailid: {
    userIndex: 3,
    fieldName: 'umEmailid',
    colDisplayName: 'Email Id',
    title: 'Email Id',
    widthOfColumn: 250,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  umMobileNumber: {
    userIndex: 4,
    fieldName: 'umMobileNumber',
    colDisplayName: 'Mobile Number',
    title: 'Mobile Number',
    widthOfColumn: 200,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  // customerName: {
  //   userIndex: 5,
  //   fieldName: 'customerNames',
  //   colDisplayName: 'Customer Name',
  //   title: 'Customer Name',
  //   widthOfColumn: 200,
  //   colType: 'text',
  //   dataType: 'text',
  //   id: '5',
  //   imgName: '',
  //   tooltipSrc: '',
  //   function: '',
  //   funParams: '',
  //   wrapData: '',
  //   isSortSupported: false,
  //   isCustomAttributeColumn: false
  // },
  customerRoleName: {
    userIndex: 6,
    fieldName: 'customerRoleName',
    colDisplayName: 'Customer Name',
    title: 'Customer Name',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  roleName: {
    userIndex: 7,
    fieldName: 'roleName',
    colDisplayName: 'User Role Name',
    title: 'User Role Name',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  umDescription: {
    userIndex: 8,
    fieldName: 'umDescription',
    colDisplayName: 'Activation Status',
    title: 'Activation Status',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },

  umAccessLevel: {
    userIndex: 8.1,
    fieldName: 'umAccessLevel',
    colDisplayName: 'Access Level',
    title: 'Access Level',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  umLoginTypeCountry: {
    userIndex: 9,
    fieldName: 'umLoginTypeCountry',
    colDisplayName: 'Login Type',
    title: 'Login Type',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  // umType: {
  //   userIndex: 10,
  //   fieldName: 'umType',
  //   colDisplayName: 'User Type',
  //   title: 'User Type',
  //   widthOfColumn: 150,
  //   colType: 'text',
  //   isAvailTooltip: true,
  //   dataType: 'text',
  //   id: '10',
  //   imgName: '',
  //   tooltipSrc: '',
  //   function: '',
  //   funParams: '',
  //   wrapData: '',
  //   isSortSupported: false,
  //   isCustomAttributeColumn: false
  // },
  umDescriptions: {
    userIndex: 11,
    fieldName: 'umDescriptions',
    colDisplayName: 'Description',
    title: 'Description',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  delete: {
    id: '12',
    fieldName: 'delete',
    colDisplayName: 'Action',
    colType: 'textwithlink',
    dataType: 'text',
    userIndex: 12,
    imgName: '',
    tooltipSrc: '',
    function: 'openUserMasterDataForDelete',
    funParams: '',
    wrapData: '',
    widthOfColumn: 75,
    isSortSupported: false,
    isCustomAttributeColumn: false,
    
  }
};
