
export const RCA_REPORT_COLUMN_HEADER = {
    srno: {
      id: '0',
      fieldName: 'srno',
      colDisplayName: 'SrNo',
      colType: 'text',
      userIndex: 0,
      imgName: '',
      tooltipSrc: '',
      dataType: 'text',
      function: '',
      funParams: '',
      wrapData: '',
      widthOfColumn: 50,
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    smSiteID: {
      userIndex: 1,
      fieldName: 'smSiteID',
      colDisplayName: 'Site Id',
      title: 'Site Id',
      widthOfColumn: 150,
      colType: 'textwithlink',
      dataType: 'text',
      id: '1',
      imgName: '',
      tooltipSrc: '',
      function: 'editRCAReportDetails',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    smSitename: {
      userIndex: 2,
      fieldName: 'smSitename',
      colDisplayName: 'Site Name',
      title: 'Site Name',
      widthOfColumn: 200,
      colType: 'textwithlink',
      dataType: 'text',
      id: '2',
      imgName: '',
      tooltipSrc: '',
      function: 'editRCAReportDetails',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    anchorOprtr: {
      userIndex: 3,
      fieldName: 'anchorOprtr',
      colDisplayName: 'Anchor Opr TR',
      title: 'Anchor Opr TR',
      widthOfColumn: 100,
      colType: 'text',
      dataType: 'text',
      id: '3',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    opcoID: {
      userIndex: 4,
      fieldName: 'opcoID',
      colDisplayName: 'Opco ID',
      title: 'Opco ID',
      widthOfColumn: 100,
      colType: 'text',
      dataType: 'text',
      id: '4',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    siteDownTime: {
      userIndex: 5,
      fieldName: 'siteDownTime',
      colDisplayName: 'Site Down Time',
      title: 'Site Down Time',
      widthOfColumn: 125,
      colType: 'text',
      dataType: 'text',
      id: '5',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    restoredTime: {
      userIndex: 6,
      fieldName: 'restoredTime',
      colDisplayName: 'Restroed Time',
      title: 'Restroed Time',
      widthOfColumn: 125,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '6',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    siteDownDuration: {
      userIndex: 7,
      fieldName: 'siteDownDuration',
      colDisplayName: 'Site Down Duration',
      title: 'Site Down Duration',
      widthOfColumn: 100,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '7',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    rca: {
      userIndex: 8,
      fieldName: 'rca',
      colDisplayName: 'RCA',
      title: 'RCA',
      widthOfColumn: 125,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '8',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    outageInMinutes: {
      userIndex: 9,
      fieldName: 'outageInMinutes',
      colDisplayName: 'Outage In Minutes',
      title: 'Outage In Minutes',
      widthOfColumn: 50,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '9',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    sla: {
      userIndex: 10,
      fieldName: 'sla',
      colDisplayName: 'SLA',
      title: 'SLA',
      widthOfColumn: 50,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '10',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    delete: {
      id: '11',
      fieldName: 'delete',
      colDisplayName: 'Action',
      colType: 'textwithlink',
      dataType: 'text',
      userIndex: 11,
      imgName: '',
      tooltipSrc: '',
      function: 'deleteRCAReportDetails',
      funParams: '',
      wrapData: '',
      widthOfColumn: 75,
      isSortSupported: false,
      isCustomAttributeColumn: false
    }
  };
  