
export const PLANNED_ENERGY_COLUMN_HEADER = {
  srno: {
    id: '0',
    fieldName: 'srno',
    colDisplayName: '',
    colType: 'text',
    userIndex: 0,
    imgName: '',
    tooltipSrc: '',
    dataType: 'checkbox',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 50,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smSitecode: {
    userIndex: 1,
    fieldName: 'smSitecode',
    colDisplayName: 'Site Code',
    title: 'Site Code',
    widthOfColumn: 100,
    colType: 'textwithlink',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: 'openPlannedEnergyDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedSolarOutputenergykwh: {
    userIndex: 2,
    fieldName: 'planedSolarOutputenergykwh',
    colDisplayName: 'Solar Output Energy (kWh)',
    title: 'Solar Output Energy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedSolarRunHrs: {
    userIndex: 3,
    fieldName: 'planedSolarRunHrs',
    colDisplayName: 'Solar Run Hrs',
    title: 'Solar Run Hrs',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedDGEnergy: {
    userIndex: 4,
    fieldName: 'planedDGEnergy',
    colDisplayName: 'DG Energy (kWh)',
    title: 'DG Energy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedDGRunHrs: {
    userIndex: 5,
    fieldName: 'planedDGRunHrs',
    colDisplayName: 'DG Run Hrs',
    title: 'DG Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedMDGEnergy: {
    userIndex: 6,
    fieldName: 'planedMDGEnergy',
    colDisplayName: 'MDG Energy (kWh)',
    title: 'MDG Energy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedMDGRunHrs: {
    userIndex: 7,
    fieldName: 'planedMDGRunHrs',
    colDisplayName: 'MDG Run Hrs',
    title: 'MDG Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattDisEnergykwh: {
    userIndex: 8,
    fieldName: 'planedBattDisEnergykwh',
    colDisplayName: 'Batt Dis Energy (kWh)',
    title: 'Batt Dis Energy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattDisRunHrs: {
    userIndex: 9,
    fieldName: 'planedBattDisRunHrs',
    colDisplayName: 'Batt Dis Run Hrs',
    title: 'Batt Dis Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattChargingEnergykwh: {
    userIndex: 10,
    fieldName: 'planedBattChargingEnergykwh',
    colDisplayName: 'Batt Charging Energy (kWh)',
    title: 'Batt Charging Energy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattChargingEnergyrunhrs: {
    userIndex: 11,
    fieldName: 'planedBattChargingEnergyrunhrs',
    colDisplayName: 'Batt Charging Energy Run Hrs',
    title: 'Batt Charging Energy Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedSolarBattRunHrs: {
    userIndex: 12,
    fieldName: 'planedSolarBattRunHrs',
    colDisplayName: 'Solar Batt Run Hrs',
    title: 'Solar Batt Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedSolarDGRunHrs: {
    userIndex: 13,
    fieldName: 'planedSolarDGRunHrs',
    colDisplayName: 'Solar DG Run Hrs',
    title: 'Solar DG Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedSolarMDGRunHrs: {
    userIndex: 14,
    fieldName: 'planedSolarMDGRunHrs',
    colDisplayName: 'Solar MDG Run Hrs',
    title: 'Solar MDG Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '14',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedTeleEnergy: {
    userIndex: 15,
    fieldName: 'planedTeleEnergy',
    colDisplayName: 'Tele Energy (kWh)',
    title: 'Tele Energy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '15',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedTeleRunHrs: {
    userIndex: 16,
    fieldName: 'planedTeleRunHrs',
    colDisplayName: 'Tele Run Hrs',
    title: 'Tele Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '16',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedCommunityLoadEnergy: {
    userIndex: 17,
    fieldName: 'planedCommunityLoadEnergy',
    colDisplayName: 'Community Load Energy (kWh)',
    title: 'Community Load Energy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '17',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedCommunityLoadRunHrs: {
    userIndex: 18,
    fieldName: 'planedCommunityLoadRunHrs',
    colDisplayName: 'Community Load Run Hrs',
    title: 'Community Load Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '18',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco1kwh: {
    userIndex: 19,
    fieldName: 'planedOpco1kwh',
    colDisplayName: 'Opco 1 (kWh)',
    title: 'Opco 1 (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '19',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco1runhrs: {
    userIndex: 20,
    fieldName: 'planedOpco1runhrs',
    colDisplayName: 'Opco 1 Run Hrs',
    title: 'Opco 1 Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '20',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco2kwh: {
    userIndex: 21,
    fieldName: 'planedOpco2kwh',
    colDisplayName: 'Opco 2 (kWh)',
    title: 'Opco 2 (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '21',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco2runhrs: {
    userIndex: 22,
    fieldName: 'planedOpco2runhrs',
    colDisplayName: 'Opco 2 Run Hrs',
    title: 'Opco 2 Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '22',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco3kwh: {
    userIndex: 23,
    fieldName: 'planedOpco3kwh',
    colDisplayName: 'Opco 3 (kWh)',
    title: 'Opco 3 (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '23',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco3runhrs: {
    userIndex: 24,
    fieldName: 'planedOpco3runhrs',
    colDisplayName: 'Opco 3 Run Hrs',
    title: 'Opco 3 Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '24',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco4kwh: {
    userIndex: 25,
    fieldName: 'planedOpco4kwh',
    colDisplayName: 'Opco 4 (kWh)',
    title: 'Opco 4 (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '25',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco4runhrs: {
    userIndex: 26,
    fieldName: 'planedOpco4runhrs',
    colDisplayName: 'Opco 4 Run Hrs',
    title: 'Opco 4 Run Hrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '26',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  delete: {
    id: '27',
    fieldName: 'delete',
    colDisplayName: 'Action',
    colType: 'textwithlink',
    dataType: 'text',
    userIndex: 27,
    imgName: '',
    tooltipSrc: '',
    function: 'openPlannedEnergyDataForDelete',
    funParams: '',
    wrapData: '',
    widthOfColumn: 75,
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
