
export const CLUSTER_COLUMN_HEADER = {
  srno: {
    userIndex: 0,
    fieldName: 'srno',
    colDisplayName: 'SrNo',
    title: 'SrNo',
    widthOfColumn: 50,
    colType: 'text',
    dataType: 'text',
    id: '0',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  crName: {
    userIndex: 1,
    fieldName: 'crName',
    colDisplayName: 'Cluster Name',
    title: 'Cluster Name',
    widthOfColumn: 150,
    colType: 'textwithlink',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: 'openClusterDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  crDefinition: {
    userIndex: 2,
    fieldName: 'crDefinition',
    colDisplayName: 'Cluster Definition',
    title: 'Cluster Definition',
    widthOfColumn: 200,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  empId: {
    userIndex: 3,
    fieldName: 'empId',
    colDisplayName: 'Employee Id',
    title: 'Employee Id',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  zoneName: {
    userIndex: 4,
    fieldName: 'zoneName',
    colDisplayName: 'Zone',
    title: 'Zone',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  crAcsysSyncstatus: {
    userIndex: 5,
    fieldName: 'crAcsysSyncstatus',
    colDisplayName: 'AcsysSyncstatus Name',
    title: 'AcsysSyncstatus Name',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  crAcsysSyncDateTime: {
    userIndex: 6,
    fieldName: 'crAcsysSyncDateTime',
    colDisplayName: 'AcsysSyncDateTime Name',
    title: 'AcsysSyncDateTime Name',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  accID: {
    userIndex: 7,
    fieldName: 'accID',
    colDisplayName: 'Acc ID Name',
    title: 'Acc ID Name',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  delete: {
    id: '8',
    fieldName: 'delete',
    colDisplayName: 'Action',
    colType: 'textwithlink',
    dataType: 'text',
    userIndex: 8,
    imgName: '',
    tooltipSrc: '',
    function: 'openClusterDataForDelete',
    funParams: '',
    wrapData: '',
    widthOfColumn: 75,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
};
