
export const BATT_LIFE_REPORTS_COLUMN_HEADER = {
    reportDate: {
      userIndex: 1,
      fieldName: 'reportDate',
      colDisplayName: 'Report Date',
      title: 'Report Date',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '1',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    // region: {
    //   userIndex: 2,
    //   fieldName: 'region',
    //   colDisplayName: 'Region',
    //   title: 'Region',
    //   widthOfColumn: 150,
    //   colType: 'text',
    //   dataType: 'text',
    //   id: '2',
    //   imgName: '',
    //   tooltipSrc: '',
    //   function: '',
    //   funParams: '',
    //   wrapData: '',
    //   isSortSupported: false,
    //   isCustomAttributeColumn: false
    // },
    cluster: {
      userIndex: 2,
      fieldName: 'cluster',
      colDisplayName: 'Cluster',
      title: 'Cluster',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '2',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    siteCode: {
      userIndex: 3,
      fieldName: 'siteCode',
      colDisplayName: 'Site Code',
      title: 'Site Code',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '3',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    // siteName: {
    //   userIndex: 4,
    //   fieldName: 'siteName',
    //   colDisplayName: 'Site Name',
    //   title: 'Site Name',
    //   widthOfColumn: 200,
    //   colType: 'text',
    //   dataType: 'text',
    //   id: '4',
    //   imgName: '',
    //   tooltipSrc: '',
    //   function: '',
    //   funParams: '',
    //   wrapData: '',
    //   isSortSupported: false,
    //   isCustomAttributeColumn: false
    // },
    initialBatteryLifeCycleCount: {
      userIndex: 4,
      fieldName: 'initialBatteryLifeCycleCount',
      colDisplayName: 'Initial Battery Life Cycle Count',
      title: 'Initial Battery Life Cycle Count',
      widthOfColumn: 200,
      colType: 'text',
      dataType: 'text',
      id: '4',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    finalBatteryLifeCycleCount: {
      userIndex: 5,
      fieldName: 'finalBatteryLifeCycleCount',
      colDisplayName: 'Final Battery Life Cycle Count',
      title: 'Final Battery Life Cycle Count',
      widthOfColumn: 200,
      colType: 'text',
      dataType: 'text',
      id: '5',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    totalBatteryCycleLifeCount: {
      userIndex: 6,
      fieldName: 'totalBatteryCycleLifeCount',
      colDisplayName: 'Total Battery Cycle Life Count',
      title: 'Total Battery Cycle Life Count',
      widthOfColumn: 200,
      colType: 'text',
      dataType: 'text',
      id: '6',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    }
  };
