
export const AppConstant = {
  CLIENT_MASTER_APP_TYPE: 0,
  LATEST_DATA1_APP_TYPE: 1,
  ALARM_STATUS_APP_TYPE: 2,

  RAW_DATA_REPORT_APP_TYPE: 4,

  CLIENT_MASTER_LISTING_TYPE: 0,
  LATEST_DATA1_LISTING_TYPE: 1,
  ALARM_STATUS_LISTING_TYPE: 2,
  RCA_REPORT_LISTING_TYPE: 3,
  RAW_DATA_REPORT_LISTING_TYPE: 4,
  TEE_POWER_TRACKER_LISTING_TYPE: 5,
  HYBRID_POWER_TRACKER_LISTING_TYPE: 6,
  TEE_ENERGY_RUN_HOURS_LISTING_TYPE: 7,
  HYBRID_ENERGY_RUN_HOURS_LISTING_TYPE: 8,

  COUNTRY_MASTER_LISTING_TYPE: 9,
  REGION_MASTER_LISTING_TYPE: 10,
  ZONE_MASTER_LISTING_TYPE: 11,
  EMPLOYEE_MASTER_LISTING_TYPE: 12,

  FILE_TRANSMITTAL_LISTING: 0,
  APPS_TRANSMITTAL_LISTING: 0,

  GET_USER_SEARCH_FILTERS_COLUMNS: 0,
  DISCUSSION_LISTING: 0,
  SAVE_SORT_DETAILS_FOR_USER: 0,

  DROPDOWN_BROADCAST_STRING: {
    DD_CLOSE: 'DD_CLOSE',
    DD_OPEN: 'DD_OPEN',
    DD_DESTROY: 'DD_DESTROY',
    DD_CHANGED: 'DD_CHANGED',
  },

  FIRST_MEETING_MOM: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_MOM'
  },
};
