
export const AppConstant = {
  CLIENT_MASTER_APP_TYPE: 0,
  LATEST_DATA1_APP_TYPE: 1,
  ALARM_STATUS_APP_TYPE: 2,

  RAW_DATA_REPORT_APP_TYPE: 4,

  CLIENT_MASTER_LISTING_TYPE: 0,
  LATEST_DATA1_LISTING_TYPE: 1,
  ALARM_STATUS_LISTING_TYPE: 2,
  RCA_REPORT_LISTING_TYPE: 3,
  RAW_DATA_REPORT_LISTING_TYPE: 4,
  TEE_POWER_TRACKER_LISTING_TYPE: 5,
  HYBRID_POWER_TRACKER_LISTING_TYPE: 6,
  TEE_ENERGY_RUN_HOURS_LISTING_TYPE: 7,
  HYBRID_ENERGY_RUN_HOURS_LISTING_TYPE: 8,
  COUNTRY_MASTER_LISTING_TYPE: 9,
  REGION_MASTER_LISTING_TYPE: 10,
  ZONE_MASTER_LISTING_TYPE: 11,
  EMPLOYEE_MASTER_LISTING_TYPE: 12,
  EMPLOYEE_ROLE_MASTER_LISTING_TYPE: 13,
  SITE_MASTER_LISTING_TYPE: 14,
  CLUSTER_MASTER_LISTING_TYPE: 15,
  SIM_MASTER_LISTING_TYPE: 16,
  FAULT_CATEGORY_LISTING_TYPE: 17,
  OUTAGE_CATEGORY_LISTING_TYPE: 18,
  ISSUE_CATEGORY_LISTING_TYPE: 19,
  REMOTE_COMMANDS_LISTING_TYPE: 20,
  VIEW_REMOTE_SITE_LISTING_TYPE: 21,
  ENERGY_BILLING_REPORT_LISTING_TYPE: 22,
  USER_LISTING_TYPE: 23,

  FILE_TRANSMITTAL_LISTING: 0,
  APPS_TRANSMITTAL_LISTING: 0,

  GET_USER_SEARCH_FILTERS_COLUMNS: 0,
  DISCUSSION_LISTING: 0,
  SAVE_SORT_DETAILS_FOR_USER: 0,

  MAX_NOTIFICATION_SHOW_COUNT: 5,
  NOTIFICATION_TIMEOUT: 3000,
  NOTIFICATION_TIME_INTERVAL: 1800000,

  DROPDOWN_BROADCAST_STRING: {
    DD_CLOSE: 'DD_CLOSE',
    DD_OPEN: 'DD_OPEN',
    DD_DESTROY: 'DD_DESTROY',
    DD_CHANGED: 'DD_CHANGED',
  },

  FIRST_MEETING_MOM: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_MOM'
  },

  REFRESH_ALARM_LISTING_INTERVAL: 120000, // 2 mins,
  ROUTE_ROLE_ID: {
    ADMIN_ROLE: '1',
    NOC1:'2',
    NOC2: '9'
  },
  ROUTE_ACCESS_ID: {
    ADMIN_ROLE:'1',
    NOC1:'2',
    NOC2:'3',
    CUSTOMER:'4'
  }
};
