
export const SITE_COLUMN_HEADER = {
  srno: {
    userIndex: 0,
    fieldName: 'srno',
    colDisplayName: 'SrNo',
    title: 'SrNo',
    widthOfColumn: 50,
    colType: 'text',
    dataType: 'text',
    id: '0',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smSiteID: {
    userIndex: 1,
    fieldName: 'smSiteID',
    colDisplayName: 'Site ID',
    title: 'Site ID',
    widthOfColumn: 100,
    colType: 'textwithlink',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: 'openSiteMasterDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smSitecode: {
    userIndex: 2,
    fieldName: 'smSitecode',
    colDisplayName: 'Site Code',
    title: 'Site Code',
    widthOfColumn: 100,
    colType: 'textwithlink',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: 'openSiteMasterDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smSitename: {
    userIndex: 3,
    fieldName: 'smSitename',
    colDisplayName: 'Site Name',
    title: 'Site Name',
    widthOfColumn: 150,
    colType: 'textwithlink',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: 'openSiteMasterDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  siteType: {
    userIndex: 4,
    fieldName: 'siteType',
    colDisplayName: 'Site Type',
    title: 'Site Type',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  clusterName: {
    userIndex: 5,
    fieldName: 'clusterName',
    colDisplayName: 'Cluster',
    title: 'Cluster',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smAddress: {
    userIndex: 6,
    fieldName: 'smAddress',
    colDisplayName: 'Address',
    title: 'Address',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smDistrict: {
    userIndex: 7,
    fieldName: 'smDistrict',
    colDisplayName: 'District',
    title: 'District',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smPincode: {
    userIndex: 8,
    fieldName: 'smPincode',
    colDisplayName: 'Pincode',
    title: 'Pincode',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  employeeId: {
    userIndex: 9,
    fieldName: 'employeeId',
    colDisplayName: 'Employee Id',
    title: 'Employee Id',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smLatitude: {
    userIndex: 10,
    fieldName: 'smLatitude',
    colDisplayName: 'Latitude',
    title: 'Latitude',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smLongitude: {
    userIndex: 11,
    fieldName: 'smLongitude',
    colDisplayName: 'Longitude',
    title: 'Longitude',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  simNumber: {
    userIndex: 12,
    fieldName: 'simNumber',
    colDisplayName: 'SIM',
    title: 'SIM',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  devicetype: {
    userIndex: 13,
    fieldName: 'devicetype',
    colDisplayName: 'Device Type',
    title: 'Device Type',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dvuniqueid: {
    userIndex: 14,
    fieldName: 'dvuniqueid',
    colDisplayName: 'Dv Unique Id',
    title: 'Dv Unique Id',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '14',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smSiteactivestatus: {
    userIndex: 15,
    fieldName: 'smSiteactivestatus',
    colDisplayName: 'Site Status',
    title: 'Site Status',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '15',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smCustomerName: {
    userIndex: 16,
    fieldName: 'smCustomerName',
    colDisplayName: 'Customer Name',
    title: 'Customer Name',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '16',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smscid: {
    userIndex: 17,
    fieldName: 'smscid',
    colDisplayName: 'Site Classification',
    title: 'Site Classification',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '17',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  accID: {
    userIndex: 18,
    fieldName: 'accID',
    colDisplayName: 'AccID Name',
    title: 'AccID Name',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '18',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dgBrand: {
    userIndex: 19,
    fieldName: 'dgBrand',
    colDisplayName: 'DG Brand Name',
    title: 'DG Brand Name',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '19',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dgTankCapacity: {
    userIndex: 20,
    fieldName: 'dgTankCapacity',
    colDisplayName: 'DG Tank Capacity',
    title: 'DG Tank Capacity',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '20',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  delete: {
    id: '21',
    fieldName: 'delete',
    colDisplayName: 'Action',
    colType: 'textwithlink',
    dataType: 'text',
    userIndex: 21,
    imgName: '',
    tooltipSrc: '',
    function: 'openSiteMasterDataForDelete',
    funParams: '',
    wrapData: '',
    widthOfColumn: 75,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
};
