
export const SIM_COLUMN_HEADER = {
  srno: {
    userIndex: 0,
    fieldName: 'srno',
    colDisplayName: 'SrNo',
    title: 'SrNo',
    widthOfColumn: 50,
    colType: 'text',
    dataType: 'text',
    id: '0',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  simID: {
    userIndex: 1,
    fieldName: 'simID',
    colDisplayName: 'Sim Id',
    title: 'Sim Id',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  simNumber: {
    userIndex: 2,
    fieldName: 'simNumber',
    colDisplayName: 'Sim Number',
    title: 'Sim Number',
    widthOfColumn: 150,
    colType: 'textwithlink',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: 'openSimDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  clCircleID: {
    userIndex: 3,
    fieldName: 'clCircleID',
    colDisplayName: 'CI Circle ID',
    title: 'CI Circle ID',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  gsmOPID: {
    userIndex: 4,
    fieldName: 'gsmOPID',
    colDisplayName: 'GSM OP ID',
    title: 'GSM OP ID',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  acAccID: {
    userIndex: 5,
    fieldName: 'acAccID',
    colDisplayName: 'Ac Acc ID',
    title: 'Ac Acc ID',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  delete: {
    id: '6',
    fieldName: 'delete',
    colDisplayName: 'Action',
    colType: 'textwithlink',
    dataType: 'text',
    userIndex: 6,
    imgName: '',
    tooltipSrc: '',
    function: 'openSimDataForDelete',
    funParams: '',
    wrapData: '',
    widthOfColumn: 75,
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
