
export const VIEW_REMOTE_DATA_COLUMN_HEADER = {
  srno: {
    userIndex: 0,
    fieldName: 'srno',
    colDisplayName: 'SrNo',
    title: 'SrNo',
    widthOfColumn: 50,
    colType: 'text',
    dataType: 'text',
    id: '0',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  command: {
    userIndex: 1,
    fieldName: 'command',
    colDisplayName: 'Commands',
    title: 'Commands',
    widthOfColumn: 250,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  triggerTime: {
    userIndex: 2,
    fieldName: 'triggerTime',
    colDisplayName: 'Last Trigger Time',
    title: 'Last Trigger Time',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  status: {
    userIndex: 3,
    fieldName: 'status',
    colDisplayName: 'Status',
    title: 'Status',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  configureValue: {
    userIndex: 4,
    fieldName: 'configureValue',
    colDisplayName: 'Last Configured Value',
    title: 'Last Configured Value',
    widthOfColumn: 200,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  edit: {
    userIndex: 5,
    fieldName: 'edit',
    colDisplayName: 'Trigger',
    title: 'Trigger',
    widthOfColumn: 150,
    colType: 'textwithlink',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: 'openRemoteDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
