
export const ZONE_COLUMN_HEADER = {
  checkbox: {
    id: '0',
    fieldName: 'srno',
    colDisplayName: '',
    colType: 'checkbox',
    userIndex: -1,
    imgName: '',
    tooltipSrc: '',
    dataType: 'checkbox',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 35,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  znZone: {
    userIndex: 1,
    fieldName: 'znZone',
    colDisplayName: 'Zone',
    title: 'Zone',
    widthOfColumn: 150,
    colType: 'textwithlink',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: 'openZoneDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  cmID: {
    userIndex: 2,
    fieldName: 'cmID',
    colDisplayName: 'Country',
    title: 'Country',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  rgRegionID: {
    userIndex: 3,
    fieldName: 'rgRegionID',
    colDisplayName: 'Region',
    title: 'Region',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  znAcsysSyncstatus: {
    userIndex: 4,
    fieldName: 'znAcsysSyncstatus',
    colDisplayName: 'AcsysSyncstatus Name',
    title: 'AcsysSyncstatus Name',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  znAcsysSyncDateTime: {
    userIndex: 5,
    fieldName: 'znAcsysSyncDateTime',
    colDisplayName: 'AcsysSyncDateTime Name',
    title: 'AcsysSyncDateTime Name',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  accID: {
    userIndex: 6,
    fieldName: 'accID',
    colDisplayName: 'AccID Name',
    title: 'AccID Name',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
