
export const ZONE_COLUMN_HEADER = {
  srno: {
    userIndex: 0,
    fieldName: 'srno',
    colDisplayName: 'SrNo',
    title: 'SrNo',
    widthOfColumn: 50,
    colType: 'text',
    dataType: 'text',
    id: '0',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  znZone: {
    userIndex: 1,
    fieldName: 'znZone',
    colDisplayName: 'Zone',
    title: 'Zone',
    widthOfColumn: 150,
    colType: 'textwithlink',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: 'openZoneDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  country: {
    userIndex: 2,
    fieldName: 'country',
    colDisplayName: 'Country',
    title: 'Country',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  region: {
    userIndex: 3,
    fieldName: 'region',
    colDisplayName: 'Region',
    title: 'Region',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  znAcsysSyncstatus: {
    userIndex: 4,
    fieldName: 'znAcsysSyncstatus',
    colDisplayName: 'AcsysSyncstatus Name',
    title: 'AcsysSyncstatus Name',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  znAcsysSyncDateTime: {
    userIndex: 5,
    fieldName: 'znAcsysSyncDateTime',
    colDisplayName: 'AcsysSyncDateTime Name',
    title: 'AcsysSyncDateTime Name',
    widthOfColumn: 175,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  accID: {
    userIndex: 6,
    fieldName: 'accID',
    colDisplayName: 'AccID Name',
    title: 'AccID Name',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  delete: {
    id: '7',
    fieldName: 'delete',
    colDisplayName: 'Action',
    colType: 'textwithlink',
    dataType: 'text',
    userIndex: 7,
    imgName: '',
    tooltipSrc: '',
    function: 'openZoneDataForDelete',
    funParams: '',
    wrapData: '',
    widthOfColumn: 75,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
};
