
export const BATT_LIFE_REPORTS_COLUMN_HEADER = {
    srno: {
      id: '0',
      fieldName: 'srno',
      colDisplayName: 'SrNo',
      colType: 'text',
      userIndex: 0,
      imgName: '',
      tooltipSrc: '',
      dataType: 'text',
      function: '',
      funParams: '',
      wrapData: '',
      widthOfColumn: 50,
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    siteId: {
      userIndex: 1,
      fieldName: 'siteId',
      colDisplayName: 'Site ID',
      title: 'Site ID',
      widthOfColumn: 100,
      colType: 'text',
      dataType: 'text',
      id: '1',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    region: {
      userIndex: 2,
      fieldName: 'region',
      colDisplayName: 'Region',
      title: 'Region',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '2',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    regionName: {
      userIndex: 3,
      fieldName: 'regionName',
      colDisplayName: 'Region Name',
      title: 'Region Name',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '3',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    cluster: {
      userIndex: 4,
      fieldName: 'cluster',
      colDisplayName: 'Cluster',
      title: 'Cluster',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '4',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    siteCode: {
      userIndex: 5,
      fieldName: 'siteCode',
      colDisplayName: 'Site Code',
      title: 'Site Code',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '5',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    siteName: {
      userIndex: 6,
      fieldName: 'siteName',
      colDisplayName: 'Site Name',
      title: 'Site Name',
      widthOfColumn: 200,
      colType: 'text',
      dataType: 'text',
      id: '6',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    customerId: {
      userIndex: 7,
      fieldName: 'customerId',
      colDisplayName: 'Customer ID',
      title: 'Customer ID',
      widthOfColumn: 100,
      colType: 'text',
      dataType: 'text',
      id: '7',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    customerName: {
      userIndex: 8,
      fieldName: 'customerName',
      colDisplayName: 'Customer Name',
      title: 'Customer Name',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '8',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    siteTypeId: {
      userIndex: 9,
      fieldName: 'siteTypeId',
      colDisplayName: 'Site Type ID',
      title: 'Site Type ID',
      widthOfColumn: 100,
      colType: 'text',
      dataType: 'text',
      id: '9',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    siteTypeName: {
      userIndex: 10,
      fieldName: 'siteTypeName',
      colDisplayName: 'Site Type Name',
      title: 'Site Type Name',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '10',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    powerSourceId: {
      userIndex: 11,
      fieldName: 'powerSourceId',
      colDisplayName: 'Power Source ID',
      title: 'Power Source ID',
      widthOfColumn: 100,
      colType: 'text',
      dataType: 'text',
      id: '11',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    powerSourceName: {
      userIndex: 12,
      fieldName: 'powerSourceName',
      colDisplayName: 'Power Source Name',
      title: 'Power Source Name',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '12',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    reportDate: {
      userIndex: 13,
      fieldName: 'reportDate',
      colDisplayName: 'Report Date',
      title: 'Report Date',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '13',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    reportMonth: {
      userIndex: 14,
      fieldName: 'reportMonth',
      colDisplayName: 'Report Month',
      title: 'Report Month',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '14',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    reportYear: {
      userIndex: 15,
      fieldName: 'reportYear',
      colDisplayName: 'Report Year',
      title: 'Report Year',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '15',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    startDateTime: {
      userIndex: 16,
      fieldName: 'startDateTime',
      colDisplayName: 'Start DateTime',
      title: 'Start DateTime',
      widthOfColumn: 200,
      colType: 'text',
      dataType: 'text',
      id: '16',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    endDateTime: {
      userIndex: 17,
      fieldName: 'endDateTime',
      colDisplayName: 'End DateTime',
      title: 'End DateTime',
      widthOfColumn: 200,
      colType: 'text',
      dataType: 'text',
      id: '17',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    initialBatteryLifeCycleCount: {
      userIndex: 18,
      fieldName: 'initialBatteryLifeCycleCount',
      colDisplayName: 'Initial Battery Life Cycle Count',
      title: 'Initial Battery Life Cycle Count',
      widthOfColumn: 200,
      colType: 'text',
      dataType: 'text',
      id: '18',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    finalBatteryLifeCycleCount: {
      userIndex: 19,
      fieldName: 'finalBatteryLifeCycleCount',
      colDisplayName: 'Final Battery Life Cycle Count',
      title: 'Final Battery Life Cycle Count',
      widthOfColumn: 200,
      colType: 'text',
      dataType: 'text',
      id: '19',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    totalBatteryCycleLifeCount: {
      userIndex: 20,
      fieldName: 'totalBatteryCycleLifeCount',
      colDisplayName: 'Total Battery Cycle Life Count',
      title: 'Total Battery Cycle Life Count',
      widthOfColumn: 200,
      colType: 'text',
      dataType: 'text',
      id: '20',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    }
  };
