
export const TEE_ENERGY_RUN_HOURS_COLUMN_HEADER = {
  checkbox: {
    id: '0',
    fieldName: 'srno',
    colDisplayName: '',
    colType: 'checkbox',
    userIndex: -1,
    imgName: '',
    tooltipSrc: '',
    dataType: 'checkbox',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 35,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  tranDate: {
    userIndex: 1,
    fieldName: 'tranDate',
    colDisplayName: 'Date',
    title: 'Date',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smSiteCode: {
    userIndex: 2,
    fieldName: 'smSiteCode',
    colDisplayName: 'Site ID',
    title: 'Site ID',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  znZone: {
    userIndex: 3,
    fieldName: 'znZone',
    colDisplayName: 'Zone',
    title: 'Zone',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  crName: {
    userIndex: 4,
    fieldName: 'crName',
    colDisplayName: 'Cluster',
    title: 'Cluster',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  rgRegion: {
    userIndex: 5,
    fieldName: 'rgRegion',
    colDisplayName: 'Region',
    title: 'Region',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  devicetype: {
    userIndex: 6,
    fieldName: 'devicetype',
    colDisplayName: 'Device Type',
    title: 'Device Type',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opco1kwh: {
    userIndex: 7,
    fieldName: 'opco1kwh',
    colDisplayName: 'Opco_1 (kWh)',
    title: 'Opco_1 (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opco1runhrs: {
    userIndex: 8,
    fieldName: 'opco1runhrs',
    colDisplayName: 'Opco1 Runhrs',
    title: 'Opco1 Runhrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco1kwh: {
    userIndex: 9,
    fieldName: 'planedOpco1kwh',
    colDisplayName: 'Planed Opco_1 (kWh)',
    title: 'Planed Opco_1 (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco1runhrs: {
    userIndex: 10,
    fieldName: 'planedOpco1runhrs',
    colDisplayName: 'Planed Opco1 Runhrs',
    title: 'Planed Opco1 Runhrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opco2kwh: {
    userIndex: 11,
    fieldName: 'opco2kwh',
    colDisplayName: 'Opco_2 (kWh)',
    title: 'Opco_2 (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opco2runhrs: {
    userIndex: 12,
    fieldName: 'opco2runhrs',
    colDisplayName: 'Opco2 Runhrs',
    title: 'Opco2 Runhrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco2kwh: {
    userIndex: 13,
    fieldName: 'planedOpco2kwh',
    colDisplayName: 'Planed Opco_2 (kWh)',
    title: 'Planed Opco_2 (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco2runhrs: {
    userIndex: 14,
    fieldName: 'planedOpco2runhrs',
    colDisplayName: 'Planed Opco2 Runhrs',
    title: 'Planed Opco2 Runhrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '14',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },

  opco3kwh: {
    userIndex: 15,
    fieldName: 'opco3kwh',
    colDisplayName: 'Opco_3 (kWh)',
    title: 'Opco_3 (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '15',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opco3runhrs: {
    userIndex: 16,
    fieldName: 'opco3runhrs',
    colDisplayName: 'Opco3 Runhrs',
    title: 'Opco3 Runhrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '16',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco3kwh: {
    userIndex: 17,
    fieldName: 'planedOpco3kwh',
    colDisplayName: 'Planed Opco_3 (kWh)',
    title: 'Planed Opco_3 (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '17',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco3runhrs: {
    userIndex: 18,
    fieldName: 'planedOpco3runhrs',
    colDisplayName: 'Planed Opco3 Runhrs',
    title: 'Planed Opco3 Runhrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '18',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },

  opco4kwh: {
    userIndex: 19,
    fieldName: 'opco4kwh',
    colDisplayName: 'Opco_4 (kWh)',
    title: 'Opco_4 (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '19',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opco4runhrs: {
    userIndex: 20,
    fieldName: 'opco4runhrs',
    colDisplayName: 'Opco4 Runhrs',
    title: 'Opco4 Runhrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '20',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco4kwh: {
    userIndex: 21,
    fieldName: 'planedOpco4kwh',
    colDisplayName: 'Planed Opco_4 (kWh)',
    title: 'Planed Opco_4 (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '21',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco4runhrs: {
    userIndex: 22,
    fieldName: 'planedOpco4runhrs',
    colDisplayName: 'Planed Opco4 Runhrs',
    title: 'Planed Opco4 Runhrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '22',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },

  teleEnergykwh: {
    userIndex: 23,
    fieldName: 'teleEnergykwh',
    colDisplayName: 'TeleEnergy (kWh)',
    title: 'TeleEnergy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '23',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  telerunhrs: {
    userIndex: 24,
    fieldName: 'telerunhrs',
    colDisplayName: 'Tele_Runhrs',
    title: 'Tele_Runhrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '24',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedTeleEnergy: {
    userIndex: 25,
    fieldName: 'planedTeleEnergy',
    colDisplayName: 'Planed TeleEnergy (kWh)',
    title: 'Planed TeleEnergy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '25',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedTeleRunHrs: {
    userIndex: 26,
    fieldName: 'planedTeleRunHrs',
    colDisplayName: 'Planed Tele_Runhrs',
    title: 'Planed Tele_Runhrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '26',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battDisEnergykwh: {
    userIndex: 27,
    fieldName: 'battDisEnergykwh',
    colDisplayName: 'Batt_DisEnergy (kWh)',
    title: 'Batt_DisEnergy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '27',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battDisRunHrs: {
    userIndex: 28,
    fieldName: 'battDisRunHrs',
    colDisplayName: 'Batt_Dis_RunHrs',
    title: 'Batt_Dis_RunHrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '28',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattDisEnergykwh: {
    userIndex: 29,
    fieldName: 'planedBattDisEnergykwh',
    colDisplayName: 'Planed Batt_DisEnergy (kWh)',
    title: 'Planed Batt_DisEnergy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '29',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattDisRunHrs: {
    userIndex: 30,
    fieldName: 'planedBattDisRunHrs',
    colDisplayName: 'Planed Batt_Dis_RunHrs',
    title: 'Planed Batt_Dis_RunHrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '30',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battChargingEnergykwh: {
    userIndex: 31,
    fieldName: 'battChargingEnergykwh',
    colDisplayName: 'Batt_ChargingEnergy (kWh)',
    title: 'Batt_ChargingEnergy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '31',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battChargingRunHrs: {
    userIndex: 32,
    fieldName: 'battChargingRunHrs',
    colDisplayName: 'Batt_ChargingRunHrs',
    title: 'Batt_ChargingRunHrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '32',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattChargingEnergykwh: {
    userIndex: 33,
    fieldName: 'planedBattChargingEnergykwh',
    colDisplayName: 'Planed Batt_ChargingEnergy (kWh)',
    title: 'Planed Batt_ChargingEnergy (kWh)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '33',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattChargingEnergyrunhrs: {
    userIndex: 34,
    fieldName: 'planedBattChargingEnergyrunhrs',
    colDisplayName: 'Planed Batt_ChargingRunHrs',
    title: 'Planed Batt_ChargingRunHrs',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '34',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
