
export const TEE_ENERGY_RUN_HOURS_COLUMN_HEADER = {
  checkbox: {
    id: '0',
    fieldName: 'srno',
    colDisplayName: '',
    colType: 'checkbox',
    userIndex: -1,
    imgName: '',
    tooltipSrc: '',
    dataType: 'checkbox',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 35,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  tranDate: {
    userIndex: 1,
    fieldName: 'tranDate',
    colDisplayName: 'Trans Date',
    title: 'Trans Date',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smsitecode: {
    userIndex: 2,
    fieldName: 'smsitecode',
    colDisplayName: 'Site ID',
    title: 'Site ID',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  znZone: {
    userIndex: 2.2,
    fieldName: 'znZone',
    colDisplayName: 'Zone',
    title: 'Zone',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  crName: {
    userIndex: 2.3,
    fieldName: 'crName',
    colDisplayName: 'Cluster',
    title: 'Cluster',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  rgRegion: {
    userIndex: 2.1,
    fieldName: 'rgRegion',
    colDisplayName: 'Region',
    title: 'Region',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  devicetype: {
    userIndex: 6,
    fieldName: 'devicetype',
    colDisplayName: 'Device Type',
    title: 'Device Type',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opco1kwh: {
    userIndex: 7,
    fieldName: 'opco1kwh',
    colDisplayName: 'Opco1 (kWh)',
    title: 'Opco1 (kWh)',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opco1runhrs: {
    userIndex: 8,
    fieldName: 'opco1runhrs',
    colDisplayName: 'Opco1 Runhrs',
    title: 'Opco1 Runhrs',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco1kwh: {
    userIndex: 9,
    fieldName: 'planedOpco1kwh',
    colDisplayName: 'Planed Opco1 (kWh)',
    title: 'Planed Opco1 (kWh)',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco1runhrs: {
    userIndex: 10,
    fieldName: 'planedOpco1runhrs',
    colDisplayName: 'Planed Opco1 Runhrs',
    title: 'Planed Opco1 Runhrs',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opco2kwh: {
    userIndex: 8.2,
    fieldName: 'opco2kwh',
    colDisplayName: 'Opco2 (kWh)',
    title: 'Opco2 (kWh)',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opco2runhrs: {
    userIndex: 8.3,
    fieldName: 'opco2runhrs',
    colDisplayName: 'Opco2 Runhrs',
    title: 'Opco2 Runhrs',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco2kwh: {
    userIndex: 13,
    fieldName: 'planedOpco2kwh',
    colDisplayName: 'Planed Opco2 (kWh)',
    title: 'Planed Opco2 (kWh)',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco2runhrs: {
    userIndex: 14,
    fieldName: 'planedOpco2runhrs',
    colDisplayName: 'Planed Opco2 Runhrs',
    title: 'Planed Opco2 Runhrs',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '14',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },

  opco3kwh: {
    userIndex: 8.4,
    fieldName: 'opco3kwh',
    colDisplayName: 'Opco3 (kWh)',
    title: 'Opco3 (kWh)',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '15',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opco3runhrs: {
    userIndex: 8.5,
    fieldName: 'opco3runhrs',
    colDisplayName: 'Opco3 Runhrs',
    title: 'Opco3 Runhrs',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '16',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco3kwh: {
    userIndex: 17,
    fieldName: 'planedOpco3kwh',
    colDisplayName: 'Planed Opco3 (kWh)',
    title: 'Planed Opco3 (kWh)',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '17',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco3runhrs: {
    userIndex: 18,
    fieldName: 'planedOpco3runhrs',
    colDisplayName: 'Planed Opco3 Runhrs',
    title: 'Planed Opco3 Runhrs',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '18',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },

  opco4kwh: {
    userIndex: 8.6,
    fieldName: 'opco4kwh',
    colDisplayName: 'Opco4 (kWh)',
    title: 'Opco4 (kWh)',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '19',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opco4runhrs: {
    userIndex: 8.7,
    fieldName: 'opco4runhrs',
    colDisplayName: 'Opco4 Runhrs',
    title: 'Opco4 Runhrs',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '20',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco4kwh: {
    userIndex: 21,
    fieldName: 'planedOpco4kwh',
    colDisplayName: 'Planed Opco4 (kWh)',
    title: 'Planed Opco4 (kWh)',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '21',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedOpco4runhrs: {
    userIndex: 22,
    fieldName: 'planedOpco4runhrs',
    colDisplayName: 'Planed Opco4 Runhrs',
    title: 'Planed Opco4 Runhrs',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '22',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },

  teleEnergykwh: {
    userIndex: 6.5,
    fieldName: 'teleEnergykwh',
    colDisplayName: 'Tele Energy (kWh)',
    title: 'Tele Energy (kWh)',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '23',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  telerunhrs: {
    userIndex: 8.1,
    fieldName: 'telerunhrs',
    colDisplayName: 'Tele Run Hours',
    title: 'Tele Run Hours',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '24',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedTeleEnergy: {
    userIndex: 25,
    fieldName: 'planedTeleEnergy',
    colDisplayName: 'Planed Tele Energy (kWh)',
    title: 'Planed Tele Energy (kWh)',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '25',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedTeleRunHrs: {
    userIndex: 26,
    fieldName: 'planedTeleRunHrs',
    colDisplayName: 'Planed Tele Run Hours',
    title: 'Planed Tele Run Hours',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '26',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battDisEnergykwh: {
    userIndex: 6.3,
    fieldName: 'battDisEnergykwh',
    colDisplayName: 'Batt DisEnergy (kWh)',
    title: 'Batt DisEnergy (kWh)',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '27',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battDisRunHrs: {
    userIndex: 6.4,
    fieldName: 'battDisRunHrs',
    colDisplayName: 'Batt Dis Run Hours',
    title: 'Batt Dis Run Hours',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '28',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattDisEnergykwh: {
    userIndex: 29,
    fieldName: 'planedBattDisEnergykwh',
    colDisplayName: 'Planed Batt DisEnergy (kWh)',
    title: 'Planed Batt DisEnergy (kWh)',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '29',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattDisRunHrs: {
    userIndex: 30,
    fieldName: 'planedBattDisRunHrs',
    colDisplayName: 'Planed Batt Dis RunHrs',
    title: 'Planed Batt Dis RunHrs',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '30',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battChargingEnergykwh: {
    userIndex: 6.1,
    fieldName: 'battChargingEnergykwh',
    colDisplayName: 'Batt Charging Energy (kWh)',
    title: 'Batt Charging Energy (kWh)',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '31',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battChargingRunHrs: {
    userIndex: 6.2,
    fieldName: 'battChargingRunHrs',
    colDisplayName: 'Batt Charging RunHrs',
    title: 'Batt Charging RunHrs',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '32',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattChargingEnergykwh: {
    userIndex: 33,
    fieldName: 'planedBattChargingEnergykwh',
    colDisplayName: 'Planed Batt Charging Energy (kWh)',
    title: 'Planed Batt Charging Energy (kWh)',
    widthOfColumn: 275,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '33',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattChargingEnergyrunhrs: {
    userIndex: 34,
    fieldName: 'planedBattChargingEnergyrunhrs',
    colDisplayName: 'Planed Batt Charging RunHrs',
    title: 'Planed Batt Charging RunHrs',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '34',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
