
export const EMPLOYEE_COLUMN_HEADER = {
  srno: {
    id: '0',
    fieldName: 'srno',
    colDisplayName: 'SrNo',
    colType: 'text',
    userIndex: 0,
    imgName: '',
    tooltipSrc: '',
    dataType: 'text',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 50,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  emEmployeeID: {
    userIndex: 1,
    fieldName: 'emEmployeeID',
    colDisplayName: 'Employee Id',
    title: 'Employee Id',
    widthOfColumn: 150,
    colType: 'textwithlink',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: 'openEmployeeDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  empRoleName: {
    userIndex: 2,
    fieldName: 'empRoleName',
    colDisplayName: 'Role',
    title: 'Role',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  emFirstName: {
    userIndex: 3,
    fieldName: 'emFirstName',
    colDisplayName: 'First Name',
    title: 'First Name',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  emLastName: {
    userIndex: 4,
    fieldName: 'emLastName',
    colDisplayName: 'Last Name',
    title: 'Last Name',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  emContactNo: {
    userIndex: 5,
    fieldName: 'emContactNo',
    colDisplayName: 'Contact No',
    title: 'Contact No',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  emEmail: {
    userIndex: 6,
    fieldName: 'emEmail',
    colDisplayName: 'Email',
    title: 'Email',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  regionName: {
    userIndex: 7,
    fieldName: 'regionName',
    colDisplayName: 'Region',
    title: 'Region',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  zoneName: {
    userIndex: 8,
    fieldName: 'zoneName',
    colDisplayName: 'Zone',
    title: 'Zone',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  // emERPLocation: {
  //   userIndex: 9,
  //   fieldName: 'emERPLocation',
  //   colDisplayName: 'ERP Location',
  //   title: 'ERP Location',
  //   widthOfColumn: 150,
  //   colType: 'text',
  //   isAvailTooltip: true,
  //   dataType: 'text',
  //   id: '9',
  //   imgName: '',
  //   tooltipSrc: '',
  //   function: '',
  //   funParams: '',
  //   wrapData: '',
  //   isSortSupported: false,
  //   isCustomAttributeColumn: false
  // },
  emLocationName: {
    userIndex: 10,
    fieldName: 'emLocationName',
    colDisplayName: 'Employee Location',
    title: 'Employee Location',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  emLatitude: {
    userIndex: 11,
    fieldName: 'emLatitude',
    colDisplayName: 'Latitude',
    title: 'Latitude',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  emLongitude: {
    userIndex: 12,
    fieldName: 'emLongitude',
    colDisplayName: 'Longitude',
    title: 'Longitude',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  emEntryDate: {
    userIndex: 13,
    fieldName: 'emEntryDate',
    colDisplayName: 'Entry Date',
    title: 'Entry Date',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  emExitDate: {
    userIndex: 14,
    fieldName: 'emExitDate',
    colDisplayName: 'Exit Date',
    title: 'Exit Date',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '14',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  emEscalationMode: {
    userIndex: 15,
    fieldName: 'emEscalationMode',
    colDisplayName: 'Escalation Mode',
    title: 'Escalation Mode',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '15',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  // emAcsysEmployeeID: {
  //   userIndex: 16,
  //   fieldName: 'emAcsysEmployeeID',
  //   colDisplayName: 'Acsys Employee ID',
  //   title: 'Acsys Employee ID',
  //   widthOfColumn: 150,
  //   colType: 'text',
  //   isAvailTooltip: true,
  //   dataType: 'text',
  //   id: '16',
  //   imgName: '',
  //   tooltipSrc: '',
  //   function: '',
  //   funParams: '',
  //   wrapData: '',
  //   isSortSupported: false,
  //   isCustomAttributeColumn: false
  // },
  // emAcsysEmployeeSyncstatus: {
  //   userIndex: 17,
  //   fieldName: 'emAcsysEmployeeSyncstatus',
  //   colDisplayName: 'Acsys Employee Sync status',
  //   title: 'Acsys Employee Sync status',
  //   widthOfColumn: 150,
  //   colType: 'text',
  //   isAvailTooltip: true,
  //   dataType: 'text',
  //   id: '17',
  //   imgName: '',
  //   tooltipSrc: '',
  //   function: '',
  //   funParams: '',
  //   wrapData: '',
  //   isSortSupported: false,
  //   isCustomAttributeColumn: false
  // },
  // emAcsysEmployeeUpdatedDt: {
  //   userIndex: 18,
  //   fieldName: 'emAcsysEmployeeUpdatedDt',
  //   colDisplayName: 'Acsys Employee Updated Date',
  //   title: 'Acsys Employee Updated Date',
  //   widthOfColumn: 150,
  //   colType: 'text',
  //   isAvailTooltip: true,
  //   dataType: 'text',
  //   id: '18',
  //   imgName: '',
  //   tooltipSrc: '',
  //   function: '',
  //   funParams: '',
  //   wrapData: '',
  //   isSortSupported: false,
  //   isCustomAttributeColumn: false
  // },
  // keID: {
  //   userIndex: 19,
  //   fieldName: 'keID',
  //   colDisplayName: 'ke ID',
  //   title: 'ke ID',
  //   widthOfColumn: 150,
  //   colType: 'text',
  //   isAvailTooltip: true,
  //   dataType: 'text',
  //   id: '19',
  //   imgName: '',
  //   tooltipSrc: '',
  //   function: '',
  //   funParams: '',
  //   wrapData: '',
  //   isSortSupported: false,
  //   isCustomAttributeColumn: false
  // },
  // emNotification: {
  //   userIndex: 20,
  //   fieldName: 'emNotification',
  //   colDisplayName: 'Employee Notification',
  //   title: 'Employee Notification',
  //   widthOfColumn: 150,
  //   colType: 'text',
  //   isAvailTooltip: true,
  //   dataType: 'text',
  //   id: '20',
  //   imgName: '',
  //   tooltipSrc: '',
  //   function: '',
  //   funParams: '',
  //   wrapData: '',
  //   isSortSupported: false,
  //   isCustomAttributeColumn: false
  // },
  // accID: {
  //   userIndex: 21,
  //   fieldName: 'accID',
  //   colDisplayName: 'AccID Name',
  //   title: 'AccID Name',
  //   widthOfColumn: 150,
  //   colType: 'text',
  //   isAvailTooltip: true,
  //   dataType: 'text',
  //   id: '21',
  //   imgName: '',
  //   tooltipSrc: '',
  //   function: '',
  //   funParams: '',
  //   wrapData: '',
  //   isSortSupported: false,
  //   isCustomAttributeColumn: false
  // },
  delete: {
    id: '22',
    fieldName: 'delete',
    colDisplayName: 'Action',
    colType: 'textwithlink',
    dataType: 'text',
    userIndex: 22,
    imgName: '',
    tooltipSrc: '',
    function: 'openEmployeeDataForDelete',
    funParams: '',
    wrapData: '',
    widthOfColumn: 75,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
};
