
export const HYBRID_POWER_TRACKER_COLUMN_HEADER = {
  checkbox: {
    id: '0',
    fieldName: 'srno',
    colDisplayName: '',
    colType: 'checkbox',
    userIndex: -1,
    imgName: '',
    tooltipSrc: '',
    dataType: 'checkbox',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 35,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  region: {
    userIndex: 1,
    fieldName: 'region',
    colDisplayName: 'Region',
    title: 'Region',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smSiteCode: {
    userIndex: 2,
    fieldName: 'smSiteCode',
    colDisplayName: 'Site ID',
    title: 'Site ID',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  datetime: {
    userIndex: 3,
    fieldName: 'datetime',
    colDisplayName: 'Date Time',
    title: 'Date Time',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  engineerName: {
    userIndex: 4,
    fieldName: 'engineerName',
    colDisplayName: 'Engineer Name',
    title: 'Engineer Name',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  powersource: {
    userIndex: 5,
    fieldName: 'powersource',
    colDisplayName: 'Power Source',
    title: 'Power Source',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  sitebattvolt: {
    userIndex: 6,
    fieldName: 'sitebattvolt',
    colDisplayName: 'Site Batt Volt',
    title: 'Site Batt Volt',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battSoc: {
    userIndex: 7,
    fieldName: 'battSoc',
    colDisplayName: 'Batt SoC%',
    title: 'Batt SoC%',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  inverterInputPower: {
    userIndex: 8,
    fieldName: 'inverterInputPower',
    colDisplayName: 'Invertor I/P Power (kW)',
    title: 'Invertor I/P Power (kW)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  inverterOutputPower: {
    userIndex: 9,
    fieldName: 'inverterOutputPower',
    colDisplayName: 'Invertor O/P Power (kW)',
    title: 'Invertor O/P Power (kW)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battChargingCurrent: {
    userIndex: 10,
    fieldName: 'battChargingCurrent',
    colDisplayName: 'Batt Charging Current (A)',
    title: 'Batt Charging Current (A)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battDischargingCurrent: {
    userIndex: 11,
    fieldName: 'battDischargingCurrent',
    colDisplayName: 'Batt Discharging Current (A)',
    title: 'Batt Discharging Current (A)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dgRAmp: {
    userIndex: 12,
    fieldName: 'dgRAmp',
    colDisplayName: 'DG R Amp',
    title: 'DG R Amp',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dgYAmp: {
    userIndex: 13,
    fieldName: 'dgYAmp',
    colDisplayName: 'DG Y Amp',
    title: 'DG Y Amp',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dgBAmp: {
    userIndex: 14,
    fieldName: 'dgBAmp',
    colDisplayName: 'DG B Amp',
    title: 'DG B Amp',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '14',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dgBatVolt: {
    userIndex: 15,
    fieldName: 'dgBatVolt',
    colDisplayName: 'DG Batt Volt',
    title: 'DG Batt Volt',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '15',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  rectInputRCurrent: {
    userIndex: 16,
    fieldName: 'rectInputRCurrent',
    colDisplayName: 'React Input R Current (A)',
    title: 'React Input R Current (A)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '16',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  rectInputYCurrent: {
    userIndex: 17,
    fieldName: 'rectInputYCurrent',
    colDisplayName: 'React Input Y Current (A)',
    title: 'React Input Y Current (A)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '17',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  rectInputBCurrent: {
    userIndex: 18,
    fieldName: 'rectInputBCurrent',
    colDisplayName: 'React Input B Current (A)',
    title: 'React Input B Current (A)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '18',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  actelRCurrent: {
    userIndex: 19,
    fieldName: 'actelRCurrent',
    colDisplayName: 'Actl R Current (A)',
    title: 'Actl R Current (A)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '19',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  actelYCurrent: {
    userIndex: 20,
    fieldName: 'actelYCurrent',
    colDisplayName: 'Actl Y Current (A)',
    title: 'Actl Y Current (A)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '20',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  actelBCurrent: {
    userIndex: 21,
    fieldName: 'actelBCurrent',
    colDisplayName: 'Actl B Current (A)',
    title: 'Actl B Current (A)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '21',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
