
export const REGION_COLUMN_HEADER = {
    checkbox: {
      id: '0',
      fieldName: 'srno',
      colDisplayName: '',
      colType: 'checkbox',
      userIndex: -1,
      imgName: '',
      tooltipSrc: '',
      dataType: 'checkbox',
      function: '',
      funParams: '',
      wrapData: '',
      widthOfColumn: 35,
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    region: {
      userIndex: 1,
      fieldName: 'region',
      colDisplayName: 'Region',
      title: 'Region',
      widthOfColumn: 100,
      colType: 'text',
      dataType: 'text',
      id: '1',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    smSiteCode: {
      userIndex: 2,
      fieldName: 'smSiteCode',
      colDisplayName: 'Site ID',
      title: 'Site ID',
      widthOfColumn: 100,
      colType: 'text',
      dataType: 'text',
      id: '2',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    datetime: {
      userIndex: 3,
      fieldName: 'datetime',
      colDisplayName: 'Date Time',
      title: 'Date Time',
      widthOfColumn: 150,
      colType: 'text',
      dataType: 'text',
      id: '3',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    engineerName: {
      userIndex: 4,
      fieldName: 'engineerName',
      colDisplayName: 'Engineer Name',
      title: 'Engineer Name',
      widthOfColumn: 100,
      colType: 'text',
      dataType: 'text',
      id: '4',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    powersource: {
      userIndex: 5,
      fieldName: 'powersource',
      colDisplayName: 'Power Source',
      title: 'Power Source',
      widthOfColumn: 100,
      colType: 'text',
      dataType: 'text',
      id: '5',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    sitebattvolt: {
      userIndex: 6,
      fieldName: 'sitebattvolt',
      colDisplayName: 'Site Batt Volt',
      title: 'Site Batt Volt',
      widthOfColumn: 100,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '6',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    battSoc: {
      userIndex: 7,
      fieldName: 'battSoc',
      colDisplayName: 'Batt SoC%',
      title: 'Batt SoC%',
      widthOfColumn: 100,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '7',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    totalDcLoadCurrent: {
      userIndex: 8,
      fieldName: 'totalDcLoadCurrent',
      colDisplayName: 'Total DC Load Current',
      title: 'Total DC Load Current',
      widthOfColumn: 100,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '8',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    rectInputRCurrent: {
      userIndex: 9,
      fieldName: 'rectInputRCurrent',
      colDisplayName: 'Rect Input R Current (A)',
      title: 'Rect Input R Current (A)',
      widthOfColumn: 100,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '9',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    rectInputYCurrent: {
      userIndex: 10,
      fieldName: 'rectInputYCurrent',
      colDisplayName: 'Rect Input Y Current (A)',
      title: 'Rect Input Y Current (A)',
      widthOfColumn: 100,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '10',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    rectInputBCurrent: {
      userIndex: 11,
      fieldName: 'rectInputBCurrent',
      colDisplayName: 'Rect Input B Current (A)',
      title: 'Rect Input B Current (A)',
      widthOfColumn: 100,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '11',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    opco1LoadCurrent: {
      userIndex: 12,
      fieldName: 'opco1LoadCurrent',
      colDisplayName: 'Opco 1 Load Current (A)',
      title: 'Opco 1 Load Current (A)',
      widthOfColumn: 100,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '12',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    opco2LoadCurrent: {
      userIndex: 13,
      fieldName: 'opco2LoadCurrent',
      colDisplayName: 'Opco 2 Load Current (A)',
      title: 'Opco 2 Load Current (A)',
      widthOfColumn: 100,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '13',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    opco3LoadCurrent: {
      userIndex: 14,
      fieldName: 'opco3LoadCurrent',
      colDisplayName: 'Opco 3 Load Current (A)',
      title: 'Opco 3 Load Current (A)',
      widthOfColumn: 100,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '14',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    },
    opco4LoadCurrent: {
      userIndex: 15,
      fieldName: 'opco4LoadCurrent',
      colDisplayName: 'Opco 4 Load Current (A)',
      title: 'Opco 4 Load Current (A)',
      widthOfColumn: 100,
      colType: 'text',
      isAvailTooltip: true,
      dataType: 'text',
      id: '15',
      imgName: '',
      tooltipSrc: '',
      function: '',
      funParams: '',
      wrapData: '',
      isSortSupported: false,
      isCustomAttributeColumn: false
    }
  };
  