
export const REGION_COLUMN_HEADER = {
  delete: {
    id: '0',
    fieldName: 'delete',
    colDisplayName: 'Action',
    colType: 'textwithlink',
    dataType: 'text',
    userIndex: 0,
    imgName: '',
    tooltipSrc: '',
    function: 'openRegionDataForDelete',
    funParams: '',
    wrapData: '',
    widthOfColumn: 75,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  rgRegion: {
    userIndex: 1,
    fieldName: 'rgRegion',
    colDisplayName: 'Region',
    title: 'Region',
    widthOfColumn: 100,
    colType: 'textwithlink',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: 'openRegionDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  country: {
    userIndex: 2,
    fieldName: 'country',
    colDisplayName: 'Country',
    title: 'Country',
    widthOfColumn: 200,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  rgAcsysSyncstatus: {
    userIndex: 3,
    fieldName: 'rgAcsysSyncstatus',
    colDisplayName: 'AcsysSyncstatus Name',
    title: 'AcsysSyncstatus Name',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  rgAcsysSyncDateTime: {
    userIndex: 4,
    fieldName: 'rgAcsysSyncDateTime',
    colDisplayName: 'AcsysSyncDateTime Name',
    title: 'AcsysSyncDateTime Name',
    widthOfColumn: 175,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  accID: {
    userIndex: 5,
    fieldName: 'accID',
    colDisplayName: 'AccID Name',
    title: 'AccID Name',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
