
export const ALARM_CATEGORY_COLUMN_HEADER = {
  srno: {
    id: '0',
    fieldName: 'srno',
    colDisplayName: 'SrNo',
    colType: 'text',
    userIndex: 0,
    imgName: '',
    tooltipSrc: '',
    dataType: 'text',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 35,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smSiteCode: {
    userIndex: 1,
    fieldName: 'smSiteCode',
    colDisplayName: 'Site ID',
    title: 'Site ID',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  alarmName: {
    userIndex: 2,
    fieldName: 'alarmName',
    colDisplayName: 'Alarm Name',
    title: 'Alarm Name',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  alarmOpenTime: {
    userIndex: 3,
    fieldName: 'alarmOpenTime',
    colDisplayName: 'Alarm Open Time',
    title: 'Alarm Open Time',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  elapsedTime: {
    userIndex: 4,
    fieldName: 'elapsedTime',
    colDisplayName: 'Elapsed Time',
    title: 'Elapsed Time',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
