
export const ALARM_CATEGORY_COLUMN_HEADER = {
  srno: {
    id: '0',
    fieldName: 'srno',
    colDisplayName: 'SrNo',
    colType: 'text',
    userIndex: 0,
    imgName: '',
    tooltipSrc: '',
    dataType: 'text',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 50,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smsiteCode: {
    userIndex: 1,
    fieldName: 'smsiteCode',
    colDisplayName: 'Site ID',
    title: 'Site ID',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  alName: {
    userIndex: 2,
    fieldName: 'alName',
    colDisplayName: 'Alarm Name',
    title: 'Alarm Name',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  opentime: {
    userIndex: 3,
    fieldName: 'opentime',
    colDisplayName: 'Open Time',
    title: 'Open Time',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  closeitem: {
    userIndex: 4,
    fieldName: 'closeitem',
    colDisplayName: 'Close Time',
    title: 'Close Time',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  elapsedTime: {
    userIndex: 5,
    fieldName: 'elapsedTime',
    colDisplayName: 'Elapsed Time',
    title: 'Elapsed Time',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  alrstatus: {
    userIndex: 6,
    fieldName: 'alrstatus',
    colDisplayName: 'Alarm Status',
    title: 'Alarm Status',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  alarmcat: {
    userIndex: 7,
    fieldName: 'alarmcat',
    colDisplayName: 'Alarm Category',
    title: 'Alarm Category',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  region: {
    userIndex: 8,
    fieldName: 'region',
    colDisplayName: 'Region',
    title: 'Region',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  zone: {
    userIndex: 9,
    fieldName: 'zone',
    colDisplayName: 'Zone',
    title: 'Zone',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  clustername: {
    userIndex: 10,
    fieldName: 'clustername',
    colDisplayName: 'Cluster Name',
    title: 'Cluster Name',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  customerName: {
    userIndex: 11,
    fieldName: 'customerName',
    colDisplayName: 'Customer Name',
    title: 'Customer Name',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  engineerName: {
    userIndex: 12,
    fieldName: 'engineerName',
    colDisplayName: 'Engineer Name',
    title: 'Engineer Name',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  sitetypeid: {
    userIndex: 13,
    fieldName: 'sitetypeid',
    colDisplayName: 'Site Type',
    title: 'Site Type',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  lastUpdated: {
    userIndex: 14,
    fieldName: 'lastUpdated',
    colDisplayName: 'Last Updated',
    title: 'Last Updated',
    widthOfColumn: 120,
    colType: 'text',
    dataType: 'text',
    id: '14',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
