
export const HYBRID_ENERGY_RUN_HOURS_COLUMN_HEADER = {
  checkbox: {
    id: '0',
    fieldName: 'srno',
    colDisplayName: '',
    colType: 'checkbox',
    userIndex: -1,
    imgName: '',
    tooltipSrc: '',
    dataType: 'checkbox',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 35,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  trandate: {
    userIndex: 1,
    fieldName: 'trandate',
    colDisplayName: 'Date',
    title: 'Date',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smsitecode: {
    userIndex: 2,
    fieldName: 'smsitecode',
    colDisplayName: 'Site ID',
    title: 'Site ID',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  znZone: {
    userIndex: 3,
    fieldName: 'znZone',
    colDisplayName: 'Zone',
    title: 'Zone',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  crName: {
    userIndex: 4,
    fieldName: 'crName',
    colDisplayName: 'Cluster',
    title: 'Cluster',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  rgRegion: {
    userIndex: 5,
    fieldName: 'rgRegion',
    colDisplayName: 'Region',
    title: 'Region',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  devicetype: {
    userIndex: 6,
    fieldName: 'devicetype',
    colDisplayName: 'Device Type',
    title: 'Device Type',
    widthOfColumn: 125,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  solarOutputenergykwh: {
    userIndex: 7,
    fieldName: 'solarOutputenergykwh',
    colDisplayName: 'Solar Output Energy (kWh)',
    title: 'Solar Output Energy (kWh)',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  solarRunHrs: {
    userIndex: 8,
    fieldName: 'solarRunHrs',
    colDisplayName: 'Solar Run Hours',
    title: 'Solar Run Hours',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedSolarOutputenergykwh: {
    userIndex: 9,
    fieldName: 'planedSolarOutputenergykwh',
    colDisplayName: 'Planed Solar Output Energy (kWh)',
    title: 'Planed Solar Output Energy (kWh)',
    widthOfColumn: 275,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedSolarRunHrs: {
    userIndex: 10,
    fieldName: 'planedSolarRunHrs',
    colDisplayName: 'Planed Solar Run Hours',
    title: 'Planed Solar Run Hours',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dGEnergy: {
    userIndex: 11,
    fieldName: 'dGEnergy',
    colDisplayName: 'Genset Energy (kWh)',
    title: 'Genset Energy (kWh)',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dGRunHrs: {
    userIndex: 12,
    fieldName: 'dGRunHrs',
    colDisplayName: 'Genset Run Hours',
    title: 'Genset Run Hours',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedDGEnergy: {
    userIndex: 13,
    fieldName: 'planedDGEnergy',
    colDisplayName: 'Planed Energy (kWh)',
    title: 'Planed Energy (kWh)',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedDGRunHrs: {
    userIndex: 14,
    fieldName: 'planedDGRunHrs',
    colDisplayName: 'Planed DG Run Hours',
    title: 'Planed DG Run Hours',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '14',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },

  mDGEnergy: {
    userIndex: 15,
    fieldName: 'mDGEnergy',
    colDisplayName: 'MGenset Energy (kWh)',
    title: 'MGenset Energy (kWh)',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '15',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  mDGRunHrs: {
    userIndex: 16,
    fieldName: 'mDGRunHrs',
    colDisplayName: 'MGenset RunHrs',
    title: 'MGenset RunHrs',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '16',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedMDGEnergy: {
    userIndex: 17,
    fieldName: 'planedMDGEnergy',
    colDisplayName: 'Planed MGenset Energy (kWh)',
    title: 'Planed MGenset Energy (kWh)',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '17',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedMDGRunHrs: {
    userIndex: 18,
    fieldName: 'planedMDGRunHrs',
    colDisplayName: 'Planed MGenset RunHrs',
    title: 'Planed MGenset RunHrs',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '18',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },

  battDisEnergykwh: {
    userIndex: 19,
    fieldName: 'battDisEnergykwh',
    colDisplayName: 'Batt DisEnergy (kWh)',
    title: 'Batt DisEnergy (kWh)',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '19',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battDisRunHrs: {
    userIndex: 20,
    fieldName: 'battDisRunHrs',
    colDisplayName: 'Batt Dis Run Hours',
    title: 'Batt Dis Run Hours',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '20',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattDisEnergykwh: {
    userIndex: 21,
    fieldName: 'planedBattDisEnergykwh',
    colDisplayName: 'Planed Batt DisEnergy (kWh)',
    title: 'Planed Batt DisEnergy (kWh)',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '21',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattDisRunHrs: {
    userIndex: 22,
    fieldName: 'planedBattDisRunHrs',
    colDisplayName: 'Planed Batt Dis Run Hours',
    title: 'Planed Batt Dis Run Hours',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '22',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },

  battChargingEnergykwh: {
    userIndex: 23,
    fieldName: 'battChargingEnergykwh',
    colDisplayName: 'Batt Charging Energy (kWh)',
    title: 'Batt Charging Energy (kWh)',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '23',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  battChargingEnergyrunhrs: {
    userIndex: 24,
    fieldName: 'battChargingEnergyrunhrs',
    colDisplayName: 'Batt Charging Energy Runhrs',
    title: 'Batt Charging Energy Runhrs',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '24',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattChargingEnergykwh: {
    userIndex: 25,
    fieldName: 'planedBattChargingEnergykwh',
    colDisplayName: 'Planed Batt Charging Energy (kWh)',
    title: 'Planed Batt Charging Energy (kWh)',
    widthOfColumn: 300,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '25',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedBattChargingEnergyrunhrs: {
    userIndex: 26,
    fieldName: 'planedBattChargingEnergyrunhrs',
    colDisplayName: 'Planed Batt_ChargingEnergy Runhrs',
    title: 'Planed Batt_ChargingEnergy Runhrs',
    widthOfColumn: 300,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '26',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  solarBattRunHrs: {
    userIndex: 27,
    fieldName: 'solarBattRunHrs',
    colDisplayName: 'SolarBatt RunHrs',
    title: 'SolarBatt RunHrs',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '27',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedSolarBattRunHrs: {
    userIndex: 28,
    fieldName: 'planedSolarBattRunHrs',
    colDisplayName: 'Planed SolarBatt RunHrs',
    title: 'Planed SolarBatt RunHrs',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '28',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  solarDGRunHrs: {
    userIndex: 29,
    fieldName: 'solarDGRunHrs',
    colDisplayName: 'SolarGenset RunHrs',
    title: 'SolarGenset RunHrs',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '29',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedSolarDGRunHrs: {
    userIndex: 30,
    fieldName: 'planedSolarDGRunHrs',
    colDisplayName: 'Planed SolarGenset RunHrs',
    title: 'Planed SolarGenset RunHrs',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '30',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  solarMDGRunHrs: {
    userIndex: 31,
    fieldName: 'solarMDGRunHrs',
    colDisplayName: 'SolarMGenset RunHrs',
    title: 'SolarMGenset RunHrs',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '31',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedSolarMDGRunHrs: {
    userIndex: 32,
    fieldName: 'planedSolarMDGRunHrs',
    colDisplayName: 'Planed SolarMGenset RunHrs',
    title: 'Planed SolarMGenset RunHrs',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '32',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  teleEnergy: {
    userIndex: 33,
    fieldName: 'teleEnergy',
    colDisplayName: 'TeleEnergy (kWh)',
    title: 'TeleEnergy (kWh)',
    widthOfColumn: 175,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '33',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  teleRunHrs: {
    userIndex: 34,
    fieldName: 'teleRunHrs',
    colDisplayName: 'TeleRunHrs',
    title: 'TeleRunHrs',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '34',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedTeleEnergy: {
    userIndex: 35,
    fieldName: 'planedTeleEnergy',
    colDisplayName: 'Planed TeleEnergy (kWh)',
    title: 'Planed TeleEnergy (kWh)',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '35',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedTeleRunHrs: {
    userIndex: 36,
    fieldName: 'planedTeleRunHrs',
    colDisplayName: 'Planed TeleRunHrs',
    title: 'Planed TeleRunHrs',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '36',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  communityLoadEnergy: {
    userIndex: 37,
    fieldName: 'communityLoadEnergy',
    colDisplayName: 'CommunityLoad Energy (kWh)',
    title: 'CommunityLoad Energy (kWh)',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '37',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  communityLoadRunHrs: {
    userIndex: 38,
    fieldName: 'communityLoadRunHrs',
    colDisplayName: 'CommunityLoad RunHrs',
    title: 'CommunityLoad RunHrs',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '38',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedCommunityLoadEnergy: {
    userIndex: 39,
    fieldName: 'planedCommunityLoadEnergy',
    colDisplayName: 'Planed Community Load Energy (kWh)',
    title: 'Planed Community Load Energy (kWh)',
    widthOfColumn: 300,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '39',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  planedCommunityLoadRunHrs: {
    userIndex: 40,
    fieldName: 'planedCommunityLoadRunHrs',
    colDisplayName: 'Planed CommunityLoad RunHrs',
    title: 'Planed CommunityLoad RunHrs',
    widthOfColumn: 250,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '40',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
