export const LITHIUM_COLUMNS_16_TO_32 = {
  "smSitecode": {
    "userIndex": 0,
    "fieldName": "smSitecode",
    "colDisplayName": "Site Code",
    "title": "Site Code",
    "widthOfColumn": 150,
    "colType": "text",
    "dataType": "text",
    "id": "0",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": true,
    "isCustomAttributeColumn": false
  },
  "lastUpdated": {
    "userIndex": 1,
    "fieldName": "lastUpdated",
    "colDisplayName": "Last Updated",
    "title": "Last Updated",
    "widthOfColumn": 160,
    "colType": "text",
    "dataType": "text",
    "id": "1",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "clusterName": {
    "userIndex": 2,
    "fieldName": "clusterName",
    "colDisplayName": "Cluster Name",
    "title": "Cluster Name",
    "widthOfColumn": 150,
    "colType": "text",
    "dataType": "text",
    "id": "2",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": true,
    "isCustomAttributeColumn": false
  },
  "sitetypeid": {
    "userIndex": 3,
    "fieldName": "sitetypeid",
    "colDisplayName": "Site Type",
    "title": "Site Type",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "3",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "zone": {
    "userIndex": 4,
    "fieldName": "zone",
    "colDisplayName": "Zone",
    "title": "Zone",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "4",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "region": {
    "userIndex": 5,
    "fieldName": "region",
    "colDisplayName": "Region",
    "title": "Region",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "5",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "powersource": {
    "userIndex": 6,
    "fieldName": "powersource",
    "colDisplayName": "Power Source",
    "title": "Power Source",
    "widthOfColumn": 140,
    "colType": "text",
    "dataType": "text",
    "id": "6",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "deviceType": {
    "userIndex": 7,
    "fieldName": "deviceType",
    "colDisplayName": "Device Type",
    "title": "Device Type",
    "widthOfColumn": 140,
    "colType": "text",
    "dataType": "text",
    "id": "7",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage16": {
    "userIndex": 8,
    "fieldName": "liBattVoltage16",
    "colDisplayName": "LiBattVoltage16",
    "title": "Battery Voltage 16",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "8",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent16": {
    "userIndex": 9,
    "fieldName": "liBattCurrent16",
    "colDisplayName": "LiBattCurrent16",
    "title": "Battery Current 16",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "9",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC16": {
    "userIndex": 10,
    "fieldName": "liSOC16",
    "colDisplayName": "LiSOC16",
    "title": "State of Charge 16",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "10",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH16": {
    "userIndex": 11,
    "fieldName": "liSOH16",
    "colDisplayName": "LiSOH16",
    "title": "State of Health 16",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "11",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp16": {
    "userIndex": 12,
    "fieldName": "liBattTemp16",
    "colDisplayName": "LiBattTemp16",
    "title": "Battery Temperature 16",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "12",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage17": {
    "userIndex": 13,
    "fieldName": "liBattVoltage17",
    "colDisplayName": "LiBattVoltage17",
    "title": "Battery Voltage 17",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "13",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent17": {
    "userIndex": 14,
    "fieldName": "liBattCurrent17",
    "colDisplayName": "LiBattCurrent17",
    "title": "Battery Current 17",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "14",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC17": {
    "userIndex": 15,
    "fieldName": "liSOC17",
    "colDisplayName": "LiSOC17",
    "title": "State of Charge 17",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "15",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH17": {
    "userIndex": 16,
    "fieldName": "liSOH17",
    "colDisplayName": "LiSOH17",
    "title": "State of Health 17",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "16",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp17": {
    "userIndex": 17,
    "fieldName": "liBattTemp17",
    "colDisplayName": "LiBattTemp17",
    "title": "Battery Temperature 17",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "17",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage18": {
    "userIndex": 18,
    "fieldName": "liBattVoltage18",
    "colDisplayName": "LiBattVoltage18",
    "title": "Battery Voltage 18",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "18",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent18": {
    "userIndex": 19,
    "fieldName": "liBattCurrent18",
    "colDisplayName": "LiBattCurrent18",
    "title": "Battery Current 18",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "19",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC18": {
    "userIndex": 20,
    "fieldName": "liSOC18",
    "colDisplayName": "LiSOC18",
    "title": "State of Charge 18",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "20",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH18": {
    "userIndex": 21,
    "fieldName": "liSOH18",
    "colDisplayName": "LiSOH18",
    "title": "State of Health 18",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "21",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp18": {
    "userIndex": 22,
    "fieldName": "liBattTemp18",
    "colDisplayName": "LiBattTemp18",
    "title": "Battery Temperature 18",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "22",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage19": {
    "userIndex": 23,
    "fieldName": "liBattVoltage19",
    "colDisplayName": "LiBattVoltage19",
    "title": "Battery Voltage 19",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "23",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent19": {
    "userIndex": 24,
    "fieldName": "liBattCurrent19",
    "colDisplayName": "LiBattCurrent19",
    "title": "Battery Current 19",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "24",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC19": {
    "userIndex": 25,
    "fieldName": "liSOC19",
    "colDisplayName": "LiSOC19",
    "title": "State of Charge 19",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "25",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH19": {
    "userIndex": 26,
    "fieldName": "liSOH19",
    "colDisplayName": "LiSOH19",
    "title": "State of Health 19",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "26",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp19": {
    "userIndex": 27,
    "fieldName": "liBattTemp19",
    "colDisplayName": "LiBattTemp19",
    "title": "Battery Temperature 19",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "27",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage20": {
    "userIndex": 28,
    "fieldName": "liBattVoltage20",
    "colDisplayName": "LiVoltage 20",
    "title": "Battery Voltage 20",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "28",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent20": {
    "userIndex": 29,
    "fieldName": "liBattCurrent20",
    "colDisplayName": "LiCurrent 20",
    "title": "Battery Current 20",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "29",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC20": {
    "userIndex": 30,
    "fieldName": "liSOC20",
    "colDisplayName": "LiSOC 20",
    "title": "State of Charge 20",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "30",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH20": {
    "userIndex": 31,
    "fieldName": "liSOH20",
    "colDisplayName": "LiSOH 20",
    "title": "State of Health 20",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "31",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp20": {
    "userIndex": 32,
    "fieldName": "liBattTemp20",
    "colDisplayName": "LiTemp 20",
    "title": "Battery Temperature 20",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "32",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage21": {
    "userIndex": 33,
    "fieldName": "liBattVoltage21",
    "colDisplayName": "LiVoltage 21",
    "title": "Battery Voltage 21",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "33",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent21": {
    "userIndex": 34,
    "fieldName": "liBattCurrent21",
    "colDisplayName": "LiCurrent 21",
    "title": "Battery Current 21",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "34",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC21": {
    "userIndex": 35,
    "fieldName": "liSOC21",
    "colDisplayName": "LiSOC 21",
    "title": "State of Charge 21",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "35",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH21": {
    "userIndex": 36,
    "fieldName": "liSOH21",
    "colDisplayName": "LiSOH 21",
    "title": "State of Health 21",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "36",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp21": {
    "userIndex": 37,
    "fieldName": "liBattTemp21",
    "colDisplayName": "LiTemp 21",
    "title": "Battery Temperature 21",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "37",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage22": {
    "userIndex": 38,
    "fieldName": "liBattVoltage22",
    "colDisplayName": "LiVoltage 22",
    "title": "Battery Voltage 22",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "38",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent22": {
    "userIndex": 39,
    "fieldName": "liBattCurrent22",
    "colDisplayName": "LiCurrent 22",
    "title": "Battery Current 22",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "39",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC22": {
    "userIndex": 40,
    "fieldName": "liSOC22",
    "colDisplayName": "LiSOC 22",
    "title": "State of Charge 22",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "40",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH22": {
    "userIndex": 41,
    "fieldName": "liSOH22",
    "colDisplayName": "LiSOH 22",
    "title": "State of Health 22",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "41",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp22": {
    "userIndex": 42,
    "fieldName": "liBattTemp22",
    "colDisplayName": "LiBattTemp 22",
    "title": "Battery Temperature 22",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "42",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  
    "liBattVoltage23": {
      "userIndex": 43,
      "fieldName": "liBattVoltage23",
      "colDisplayName": "LiBattVoltage 23",
      "title": "Battery Voltage 23",
      "widthOfColumn": 130,
      "colType": "text",
      "dataType": "text",
      "id": "43",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liBattCurrent23": {
      "userIndex": 44,
      "fieldName": "liBattCurrent23",
      "colDisplayName": "LiBattCurrent 23",
      "title": "Battery Current 23",
      "widthOfColumn": 130,
      "colType": "text",
      "dataType": "text",
      "id": "44",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liSOC23": {
      "userIndex": 45,
      "fieldName": "liSOC23",
      "colDisplayName": "LiSOC23",
      "title": "State of Charge 23",
      "widthOfColumn": 120,
      "colType": "text",
      "dataType": "text",
      "id": "45",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liSOH23": {
      "userIndex": 46,
      "fieldName": "liSOH23",
      "colDisplayName": "LiSOH23",
      "title": "State of Health 23",
      "widthOfColumn": 120,
      "colType": "text",
      "dataType": "text",
      "id": "46",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liBattTemp23": {
      "userIndex": 47,
      "fieldName": "liBattTemp23",
      "colDisplayName": "LiBattTemp23",
      "title": "Battery Temperature 23",
      "widthOfColumn": 120,
      "colType": "text",
      "dataType": "text",
      "id": "47",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liBattVoltage24": {
      "userIndex": 48,
      "fieldName": "liBattVoltage24",
      "colDisplayName": "LiBattVoltage 24",
      "title": "Battery Voltage 24",
      "widthOfColumn": 130,
      "colType": "text",
      "dataType": "text",
      "id": "48",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liBattCurrent24": {
      "userIndex": 49,
      "fieldName": "liBattCurrent24",
      "colDisplayName": "LiBattCurrent 24",
      "title": "Battery Current 24",
      "widthOfColumn": 130,
      "colType": "text",
      "dataType": "text",
      "id": "49",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liSOC24": {
      "userIndex": 50,
      "fieldName": "liSOC24",
      "colDisplayName": "LiSOC24",
      "title": "State of Charge 24",
      "widthOfColumn": 120,
      "colType": "text",
      "dataType": "text",
      "id": "50",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liSOH24": {
      "userIndex": 51,
      "fieldName": "liSOH24",
      "colDisplayName": "LiSOH24",
      "title": "State of Health 24",
      "widthOfColumn": 120,
      "colType": "text",
      "dataType": "text",
      "id": "51",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liBattTemp24": {
      "userIndex": 52,
      "fieldName": "liBattTemp24",
      "colDisplayName": "LiBattTemp24",
      "title": "Battery Temperature 24",
      "widthOfColumn": 120,
      "colType": "text",
      "dataType": "text",
      "id": "52",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liBattVoltage25": {
      "userIndex": 53,
      "fieldName": "liBattVoltage25",
      "colDisplayName": "LiBattVoltage 25",
      "title": "Battery Voltage 25",
      "widthOfColumn": 130,
      "colType": "text",
      "dataType": "text",
      "id": "53",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liBattCurrent25": {
      "userIndex": 54,
      "fieldName": "liBattCurrent25",
      "colDisplayName": "LiBattCurrent 25",
      "title": "Battery Current 25",
      "widthOfColumn": 130,
      "colType": "text",
      "dataType": "text",
      "id": "54",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liSOC25": {
      "userIndex": 55,
      "fieldName": "liSOC25",
      "colDisplayName": "LiSOC25",
      "title": "State of Charge 25",
      "widthOfColumn": 120,
      "colType": "text",
      "dataType": "text",
      "id": "55",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liSOH25": {
      "userIndex": 56,
      "fieldName": "liSOH25",
      "colDisplayName": "LiSOH25",
      "title": "State of Health 25",
      "widthOfColumn": 120,
      "colType": "text",
      "dataType": "text",
      "id": "56",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liBattTemp25": {
      "userIndex": 57,
      "fieldName": "liBattTemp25",
      "colDisplayName": "LiBattTemp25",
      "title": "Battery Temperature 25",
      "widthOfColumn": 120,
      "colType": "text",
      "dataType": "text",
      "id": "57",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liBattVoltage26": {
      "userIndex": 58,
      "fieldName": "liBattVoltage26",
      "colDisplayName": "LiBattVoltage 26",
      "title": "Battery Voltage 26",
      "widthOfColumn": 130,
      "colType": "text",
      "dataType": "text",
      "id": "58",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liBattCurrent26": {
      "userIndex": 59,
      "fieldName": "liBattCurrent26",
      "colDisplayName": "LiBattCurrent 26",
      "title": "Battery Current 26",
      "widthOfColumn": 130,
      "colType": "text",
      "dataType": "text",
      "id": "59",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liSOC26": {
      "userIndex": 60,
      "fieldName": "liSOC26",
      "colDisplayName": "LiSOC26",
      "title": "State of Charge 26",
      "widthOfColumn": 120,
      "colType": "text",
      "dataType": "text",
      "id": "60",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liSOH26": {
      "userIndex": 61,
      "fieldName": "liSOH26",
      "colDisplayName": "LiSOH26",
      "title": "State of Health 26",
      "widthOfColumn": 120,
      "colType": "text",
      "dataType": "text",
      "id": "61",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liBattTemp26": {
      "userIndex": 62,
      "fieldName": "liBattTemp26",
      "colDisplayName": "LiBattTemp26",
      "title": "Battery Temperature 26",
      "widthOfColumn": 120,
      "colType": "text",
      "dataType": "text",
      "id": "62",
      "imgName": "",
      "tooltipSrc": "",
      "function": "",
      "funParams": "",
      "wrapData": "",
      "isSortSupported": false,
      "isCustomAttributeColumn": false
    },
    "liBattVoltage27": {
    "userIndex": 63,
    "fieldName": "liBattVoltage27",
    "colDisplayName": "LiBattVoltage 27",
    "title": "Battery Voltage 27",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "63",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent27": {
    "userIndex": 64,
    "fieldName": "liBattCurrent27",
    "colDisplayName": "LiBattCurrent 27",
    "title": "Battery Current 27",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "64",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC27": {
    "userIndex": 65,
    "fieldName": "liSOC27",
    "colDisplayName": "LiSOC27",
    "title": "State of Charge 27",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "65",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH27": {
    "userIndex": 66,
    "fieldName": "liSOH27",
    "colDisplayName": "LiSOH27",
    "title": "State of Health 27",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "66",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp27": {
    "userIndex": 67,
    "fieldName": "liBattTemp27",
    "colDisplayName": "LiBattTemp27",
    "title": "Battery Temperature 27",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "67",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage28": {
    "userIndex": 68,
    "fieldName": "liBattVoltage28",
    "colDisplayName": "LiBattVoltage 28",
    "title": "Battery Voltage 28",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "68",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent28": {
    "userIndex": 69,
    "fieldName": "liBattCurrent28",
    "colDisplayName": "LiBattCurrent 28",
    "title": "Battery Current 28",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "69",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC28": {
    "userIndex": 70,
    "fieldName": "liSOC28",
    "colDisplayName": "LiSOC28",
    "title": "State of Charge 28",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "70",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH28": {
    "userIndex": 71,
    "fieldName": "liSOH28",
    "colDisplayName": "LiSOH28",
    "title": "State of Health 28",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "71",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp28": {
    "userIndex": 72,
    "fieldName": "liBattTemp28",
    "colDisplayName": "LiBattTemp28",
    "title": "Battery Temperature 28",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "72",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage29": {
    "userIndex": 73,
    "fieldName": "liBattVoltage29",
    "colDisplayName": "LiBattVoltage 29",
    "title": "Battery Voltage 29",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "73",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent29": {
    "userIndex": 74,
    "fieldName": "liBattCurrent29",
    "colDisplayName": "LiBattCurrent 29",
    "title": "Battery Current 29",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "74",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC29": {
    "userIndex": 75,
    "fieldName": "liSOC29",
    "colDisplayName": "LiSOC29",
    "title": "State of Charge 29",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "75",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH29": {
    "userIndex": 76,
    "fieldName": "liSOH29",
    "colDisplayName": "LiSOH29",
    "title": "State of Health 29",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "76",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp29": {
    "userIndex": 77,
    "fieldName": "liBattTemp29",
    "colDisplayName": "LiBattTemp29",
    "title": "Battery Temperature 29",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "77",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage30": {
    "userIndex": 78,
    "fieldName": "liBattVoltage30",
    "colDisplayName": "LiBattVoltage 30",
    "title": "Battery Voltage 30",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "78",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent30": {
    "userIndex": 79,
    "fieldName": "liBattCurrent30",
    "colDisplayName": "LiBattCurrent 30",
    "title": "Battery Current 30",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "79",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC30": {
    "userIndex": 80,
    "fieldName": "liSOC30",
    "colDisplayName": "LiSOC30",
    "title": "State of Charge 30",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "80",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH30": {
    "userIndex": 81,
    "fieldName": "liSOH30",
    "colDisplayName": "LiSOH30",
    "title": "State of Health 30",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "81",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp30": {
    "userIndex": 82,
    "fieldName": "liBattTemp30",
    "colDisplayName": "LiBattTemp30",
    "title": "Battery Temperature 30",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "82",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage31": {
    "userIndex": 83,
    "fieldName": "liBattVoltage31",
    "colDisplayName": "LiBattVoltage 31",
    "title": "Battery Voltage 31",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "83",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent31": {
    "userIndex": 84,
    "fieldName": "liBattCurrent31",
    "colDisplayName": "LiBattCurrent 31",
    "title": "Battery Current 31",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "84",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC31": {
    "userIndex": 85,
    "fieldName": "liSOC31",
    "colDisplayName": "LiSOC31",
    "title": "State of Charge 31",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "85",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH31": {
    "userIndex": 86,
    "fieldName": "liSOH31",
    "colDisplayName": "LiSOH31",
    "title": "State of Health 31",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "86",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp31": {
    "userIndex": 87,
    "fieldName": "liBattTemp31",
    "colDisplayName": "LiBattTemp31",
    "title": "Battery Temperature 31",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "87",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage32": {
    "userIndex": 88,
    "fieldName": "liBattVoltage32",
    "colDisplayName": "LiBattVoltage 32",
    "title": "Battery Voltage 32",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "88",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent32": {
    "userIndex": 89,
    "fieldName": "liBattCurrent32",
    "colDisplayName": "LiBattCurrent 32",
    "title": "Battery Current 32",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "89",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC32": {
    "userIndex": 90,
    "fieldName": "liSOC32",
    "colDisplayName": "LiSOC32",
    "title": "State of Charge 32",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "90",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH32": {
    "userIndex": 91,
    "fieldName": "liSOH32",
    "colDisplayName": "LiSOH32",
    "title": "State of Health 32",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "91",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp32": {
    "userIndex": 92,
    "fieldName": "liBattTemp32",
    "colDisplayName": "LiBattTemp32",
    "title": "Battery Temperature 32",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "92",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  }
  };