export const LITHIUM_COLUMNS_1_TO_15 = {
  "smSitecode": {
    "userIndex": 0,
    "fieldName": "smSitecode",
    "colDisplayName": "Site Code",
    "title": "Site Code",
    "widthOfColumn": 150,
    "colType": "text",
    "dataType": "text",
    "id": "0",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": true,
    "isCustomAttributeColumn": false
  },
  "lastUpdated": {
    "userIndex": 1.9,
    "fieldName": "lastUpdated",
    "colDisplayName": "Last Updated",
    "title": "Last Updated",
    "widthOfColumn": 160,
    "colType": "text",
    "dataType": "text",
    "id": "1",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "clusterName": {
    "userIndex": 2.1,
    "fieldName": "clusterName",
    "colDisplayName": "Cluster Name",
    "title": "Cluster Name",
    "widthOfColumn": 150,
    "colType": "text",
    "dataType": "text",
    "id": "2",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": true,
    "isCustomAttributeColumn": false
  },
  "sitetypeid": {
    "userIndex": 2.1,
    "fieldName": "sitetypeid",
    "colDisplayName": "Site Type",
    "title": "Site Type",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "3",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "zone": {
    "userIndex": 2.3,
    "fieldName": "zone",
    "colDisplayName": "Zone",
    "title": "Zone",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "4",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "region": {
    "userIndex": 2.5,
    "fieldName": "region",
    "colDisplayName": "Region",
    "title": "Region",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "5",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "powersource": {
    "userIndex": 2.8,
    "fieldName": "powersource",
    "colDisplayName": "Power Source",
    "title": "Power Source",
    "widthOfColumn": 140,
    "colType": "text",
    "dataType": "text",
    "id": "6",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "deviceType": {
    "userIndex": 2.9,
    "fieldName": "deviceType",
    "colDisplayName": "Device Type",
    "title": "Device Type",
    "widthOfColumn": 140,
    "colType": "text",
    "dataType": "text",
    "id": "7",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage1": {
    "userIndex": 3,
    "fieldName": "liBattVoltage1",
    "colDisplayName": "LiBattVoltage1",
    "title": "Battery Voltage 1",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "3",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent1": {
    "userIndex": 4,
    "fieldName": "liBattCurrent1",
    "colDisplayName": "LiBattCurrent1",
    "title": "Battery Current 1",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "4",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC1": {
    "userIndex": 5,
    "fieldName": "liSOC1",
    "colDisplayName": "LiSOC1",
    "title": "State of Charge 1",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "5",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH1": {
    "userIndex": 6,
    "fieldName": "liSOH1",
    "colDisplayName": "LiSOH1",
    "title": "State of Health 1",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "6",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp1": {
    "userIndex": 7,
    "fieldName": "liBattTemp1",
    "colDisplayName": "LiBattTemp1",
    "title": "Battery Temperature 1",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "7",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage2": {
    "userIndex": 8,
    "fieldName": "liBattVoltage2",
    "colDisplayName": "LiBattVoltage2",
    "title": "Battery Voltage 2",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "8",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent2": {
    "userIndex": 9,
    "fieldName": "liBattCurrent2",
    "colDisplayName": "LiBattCurrent2",
    "title": "Battery Current 2",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "9",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC2": {
    "userIndex": 10,
    "fieldName": "liSOC2",
    "colDisplayName": "LiSOC2",
    "title": "State of Charge 2",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "10",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH2": {
    "userIndex": 11,
    "fieldName": "liSOH2",
    "colDisplayName": "LiSOH2",
    "title": "State of Health 2",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "11",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp2": {
    "userIndex": 12,
    "fieldName": "liBattTemp2",
    "colDisplayName": "LiBattTemp2",
    "title": "Battery Temperature 2",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "12",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage3": {
    "userIndex": 13,
    "fieldName": "liBattVoltage3",
    "colDisplayName": "LiBattVoltage3",
    "title": "Battery Voltage 3",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "13",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent3": {
    "userIndex": 14,
    "fieldName": "liBattCurrent3",
    "colDisplayName": "LiBattCurrent3",
    "title": "Battery Current 3",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "14",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC3": {
    "userIndex": 15,
    "fieldName": "liSOC3",
    "colDisplayName": "LiSOC3",
    "title": "State of Charge 3",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "15",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH3": {
    "userIndex": 16,
    "fieldName": "liSOH3",
    "colDisplayName": "LiSOH3",
    "title": "State of Health 3",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "16",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp3": {
    "userIndex": 17,
    "fieldName": "liBattTemp3",
    "colDisplayName": "LiBattTemp3",
    "title": "Battery Temperature 3",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "17",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage4": {
    "userIndex": 18,
    "fieldName": "liBattVoltage4",
    "colDisplayName": "LiBattVoltage4",
    "title": "Battery Voltage 4",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "18",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent4": {
    "userIndex": 19,
    "fieldName": "liBattCurrent4",
    "colDisplayName": "LiBattCurrent4",
    "title": "Battery Current 4",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "19",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC4": {
    "userIndex": 20,
    "fieldName": "liSOC4",
    "colDisplayName": "LiSOC4",
    "title": "State of Charge 4",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "20",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH4": {
    "userIndex": 21,
    "fieldName": "liSOH4",
    "colDisplayName": "LiSOH4",
    "title": "State of Health 4",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "21",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp4": {
    "userIndex": 22,
    "fieldName": "liBattTemp4",
    "colDisplayName": "LiBattTemp4",
    "title": "Battery Temperature 4",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "22",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage5": {
    "userIndex": 23,
    "fieldName": "liBattVoltage5",
    "colDisplayName": "LiBattVoltage5",
    "title": "Battery Voltage 5",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "23",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent5": {
    "userIndex": 24,
    "fieldName": "liBattCurrent5",
    "colDisplayName": "LiBattCurrent5",
    "title": "Battery Current 5",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "24",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC5": {
    "userIndex": 25,
    "fieldName": "liSOC5",
    "colDisplayName": "LiSOC5",
    "title": "State of Charge 5",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "25",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH5": {
    "userIndex": 26,
    "fieldName": "liSOH5",
    "colDisplayName": "LiSOH5",
    "title": "State of Health 5",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "26",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp5": {
    "userIndex": 27,
    "fieldName": "liBattTemp5",
    "colDisplayName": "LiBattTemp5",
    "title": "Battery Temperature 5",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "27",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage6": {
    "userIndex": 28,
    "fieldName": "liBattVoltage6",
    "colDisplayName": "LiBattVoltage6",
    "title": "Battery Voltage 6",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "28",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent6": {
    "userIndex": 29,
    "fieldName": "liBattCurrent6",
    "colDisplayName": "LiBattCurrent6",
    "title": "Battery Current 6",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "29",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC6": {
    "userIndex": 30,
    "fieldName": "liSOC6",
    "colDisplayName": "LiSOC6",
    "title": "State of Charge 6",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "30",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH6": {
    "userIndex": 31,
    "fieldName": "liSOH6",
    "colDisplayName": "LiSOH6",
    "title": "State of Health 6",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "31",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp6": {
    "userIndex": 32,
    "fieldName": "liBattTemp6",
    "colDisplayName": "LiBattTemp6",
    "title": "Battery Temperature 6",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "32",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage7": {
    "userIndex": 33,
    "fieldName": "liBattVoltage7",
    "colDisplayName": "LiBattVoltage7",
    "title": "Battery Voltage 7",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "33",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent7": {
    "userIndex": 34,
    "fieldName": "liBattCurrent7",
    "colDisplayName": "LiBattCurrent7",
    "title": "Battery Current 7",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "34",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC7": {
    "userIndex": 35,
    "fieldName": "liSOC7",
    "colDisplayName": "LiSOC7",
    "title": "State of Charge 7",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "35",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH7": {
    "userIndex": 36,
    "fieldName": "liSOH7",
    "colDisplayName": "LiSOH7",
    "title": "State of Health 7",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "36",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp7": {
    "userIndex": 37,
    "fieldName": "liBattTemp7",
    "colDisplayName": "LiBattTemp7",
    "title": "Battery Temperature 7",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "37",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage8": {
    "userIndex": 38,
    "fieldName": "liBattVoltage8",
    "colDisplayName": "LiBattVoltage8",
    "title": "Battery Voltage 8",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "38",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent8": {
    "userIndex": 39,
    "fieldName": "liBattCurrent8",
    "colDisplayName": "LiBattCurrent8",
    "title": "Battery Current 8",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "39",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC8": {
    "userIndex": 40,
    "fieldName": "liSOC8",
    "colDisplayName": "LiSOC8",
    "title": "State of Charge 8",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "40",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH8": {
    "userIndex": 41,
    "fieldName": "liSOH8",
    "colDisplayName": "LiSOH8",
    "title": "State of Health 8",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "41",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp8": {
    "userIndex": 42,
    "fieldName": "liBattTemp8",
    "colDisplayName": "LiBattTemp8",
    "title": "Battery Temperature 8",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "42",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage9": {
    "userIndex": 43,
    "fieldName": "liBattVoltage9",
    "colDisplayName": "LiBattVoltage9",
    "title": "Battery Voltage 9",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "43",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent9": {
    "userIndex": 44,
    "fieldName": "liBattCurrent9",
    "colDisplayName": "LiBattCurrent9",
    "title": "Battery Current 9",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "44",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC9": {
    "userIndex": 45,
    "fieldName": "liSOC9",
    "colDisplayName": "LiSOC9",
    "title": "State of Charge 9",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "45",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH9": {
    "userIndex": 46,
    "fieldName": "liSOH9",
    "colDisplayName": "LiSOH9",
    "title": "State of Health 9",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "46",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp9": {
    "userIndex": 47,
    "fieldName": "liBattTemp9",
    "colDisplayName": "LiBattTemp9",
    "title": "Battery Temperature 9",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "47",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage10": {
    "userIndex": 48,
    "fieldName": "liBattVoltage10",
    "colDisplayName": "LiBattVoltage10",
    "title": "Battery Voltage 10",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "48",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent10": {
    "userIndex": 49,
    "fieldName": "liBattCurrent10",
    "colDisplayName": "LiBattCurrent10",
    "title": "Battery Current 10",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "49",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC10": {
    "userIndex": 50,
    "fieldName": "liSOC10",
    "colDisplayName": "LiSOC10",
    "title": "State of Charge 10",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "50",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH10": {
    "userIndex": 51,
    "fieldName": "liSOH10",
    "colDisplayName": "LiSOH10",
    "title": "State of Health 10",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "51",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp10": {
    "userIndex": 52,
    "fieldName": "liBattTemp10",
    "colDisplayName": "LiBattTemp10",
    "title": "Battery Temperature 10",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "52",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage11": {
    "userIndex": 53,
    "fieldName": "liBattVoltage11",
    "colDisplayName": "LiBattVoltage11",
    "title": "Battery Voltage 11",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "53",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent11": {
    "userIndex": 54,
    "fieldName": "liBattCurrent11",
    "colDisplayName": "LiBattCurrent11",
    "title": "Battery Current 11",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "54",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC11": {
    "userIndex": 55,
    "fieldName": "liSOC11",
    "colDisplayName": "LiSOC11",
    "title": "State of Charge 11",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "55",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH11": {
    "userIndex": 56,
    "fieldName": "liSOH11",
    "colDisplayName": "LiSOH11",
    "title": "State of Health 11",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "56",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp11": {
    "userIndex": 57,
    "fieldName": "liBattTemp11",
    "colDisplayName": "LiBattTemp11",
    "title": "Battery Temperature 11",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "57",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage12": {
    "userIndex": 58,
    "fieldName": "liBattVoltage12",
    "colDisplayName": "LiBattVoltage12",
    "title": "Battery Voltage 12",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "58",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent12": {
    "userIndex": 59,
    "fieldName": "liBattCurrent12",
    "colDisplayName": "LiBattCurrent12",
    "title": "Battery Current 12",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "59",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC12": {
    "userIndex": 60,
    "fieldName": "liSOC12",
    "colDisplayName": "LiSOC12",
    "title": "State of Charge 12",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "60",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH12": {
    "userIndex": 61,
    "fieldName": "liSOH12",
    "colDisplayName": "LiSOH12",
    "title": "State of Health 12",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "61",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp12": {
    "userIndex": 62,
    "fieldName": "liBattTemp12",
    "colDisplayName": "LiBattTemp12",
    "title": "Battery Temperature 12",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "62",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage13": {
    "userIndex": 63,
    "fieldName": "liBattVoltage13",
    "colDisplayName": "LiBattVoltage13",
    "title": "Battery Voltage 13",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "63",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent13": {
    "userIndex": 64,
    "fieldName": "liBattCurrent13",
    "colDisplayName": "LiBattCurrent13",
    "title": "Battery Current 13",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "64",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC13": {
    "userIndex": 65,
    "fieldName": "liSOC13",
    "colDisplayName": "LiSOC13",
    "title": "State of Charge 13",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "65",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH13": {
    "userIndex": 66,
    "fieldName": "liSOH13",
    "colDisplayName": "LiSOH13",
    "title": "State of Health 13",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "66",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp13": {
    "userIndex": 67,
    "fieldName": "liBattTemp13",
    "colDisplayName": "LiBattTemp13",
    "title": "Battery Temperature 13",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "67",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage14": {
    "userIndex": 68,
    "fieldName": "liBattVoltage14",
    "colDisplayName": "LiBattVoltage14",
    "title": "Battery Voltage 14",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "68",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent14": {
    "userIndex": 69,
    "fieldName": "liBattCurrent14",
    "colDisplayName": "LiBattCurrent14",
    "title": "Battery Current 14",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "69",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC14": {
    "userIndex": 70,
    "fieldName": "liSOC14",
    "colDisplayName": "LiSOC14",
    "title": "State of Charge 14",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "70",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH14": {
    "userIndex": 71,
    "fieldName": "liSOH14",
    "colDisplayName": "LiSOH14",
    "title": "State of Health 14",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "71",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp14": {
    "userIndex": 72,
    "fieldName": "liBattTemp14",
    "colDisplayName": "LiBattTemp14",
    "title": "Battery Temperature 14",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "72",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage15": {
    "userIndex": 73,
    "fieldName": "liBattVoltage15",
    "colDisplayName": "LiBattVoltage15",
    "title": "Battery Voltage 15",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "73",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattCurrent15": {
    "userIndex": 74,
    "fieldName": "liBattCurrent15",
    "colDisplayName": "LiBattCurrent15",
    "title": "Battery Current 15",
    "widthOfColumn": 130,
    "colType": "text",
    "dataType": "text",
    "id": "74",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOC15": {
    "userIndex": 75,
    "fieldName": "liSOC15",
    "colDisplayName": "LiSOC15",
    "title": "State of Charge 15",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "75",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liSOH15": {
    "userIndex": 76,
    "fieldName": "liSOH15",
    "colDisplayName": "LiSOH15",
    "title": "State of Health 15",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "76",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattTemp15": {
    "userIndex": 77,
    "fieldName": "liBattTemp15",
    "colDisplayName": "LiBattTemp15",
    "title": "Battery Temperature 15",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "77",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  }
};