export const LITHIUM_COLUMNS_33_TO_48 = {
  "smSitecode": {
    "userIndex": 0,
    "fieldName": "smSitecode",
    "colDisplayName": "Site Code",
    "title": "Site Code",
    "widthOfColumn": 150,
    "colType": "text",
    "dataType": "text",
    "id": "0",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": true,
    "isCustomAttributeColumn": false
  },
  "lastUpdated": {
    "userIndex": 1,
    "fieldName": "lastUpdated",
    "colDisplayName": "Last Updated",
    "title": "Last Updated",
    "widthOfColumn": 160,
    "colType": "text",
    "dataType": "text",
    "id": "1",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "clusterName": {
    "userIndex": 2,
    "fieldName": "clusterName",
    "colDisplayName": "Cluster Name",
    "title": "Cluster Name",
    "widthOfColumn": 150,
    "colType": "text",
    "dataType": "text",
    "id": "2",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": true,
    "isCustomAttributeColumn": false
  },
  "sitetypeid": {
    "userIndex": 3,
    "fieldName": "sitetypeid",
    "colDisplayName": "Site Type",
    "title": "Site Type",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "3",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "zone": {
    "userIndex": 4,
    "fieldName": "zone",
    "colDisplayName": "Zone",
    "title": "Zone",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "4",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "region": {
    "userIndex": 5,
    "fieldName": "region",
    "colDisplayName": "Region",
    "title": "Region",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "5",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "powersource": {
    "userIndex": 6,
    "fieldName": "powersource",
    "colDisplayName": "Power Source",
    "title": "Power Source",
    "widthOfColumn": 140,
    "colType": "text",
    "dataType": "text",
    "id": "6",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "deviceType": {
    "userIndex": 7,
    "fieldName": "deviceType",
    "colDisplayName": "Device Type",
    "title": "Device Type",
    "widthOfColumn": 140,
    "colType": "text",
    "dataType": "text",
    "id": "7",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage33": { "userIndex": 8,  "fieldName": "liBattVoltage33", "colDisplayName": "LiBattVoltage 33", "title": "Battery Voltage 33",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "8",  "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent33": { "userIndex": 9,  "fieldName": "liBattCurrent33", "colDisplayName": "LiBattCurrent 33", "title": "Battery Current 33",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "9",  "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC33":         { "userIndex": 10, "fieldName": "liSOC33",         "colDisplayName": "LiSOC33",          "title": "State of Charge 33",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "10", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH33":         { "userIndex": 11, "fieldName": "liSOH33",         "colDisplayName": "LiSOH33",          "title": "State of Health 33",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "11", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp33":    { "userIndex": 12, "fieldName": "liBattTemp33",    "colDisplayName": "LiBattTemp33",     "title": "Battery Temperature 33", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "12", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage34": { "userIndex": 13, "fieldName": "liBattVoltage34", "colDisplayName": "LiBattVoltage 34", "title": "Battery Voltage 34",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "13", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent34": { "userIndex": 14, "fieldName": "liBattCurrent34", "colDisplayName": "LiBattCurrent 34", "title": "Battery Current 34",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "14", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC34":         { "userIndex": 15, "fieldName": "liSOC34",         "colDisplayName": "LiSOC34",          "title": "State of Charge 34",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "15", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH34":         { "userIndex": 16, "fieldName": "liSOH34",         "colDisplayName": "LiSOH34",          "title": "State of Health 34",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "16", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp34":    { "userIndex": 17, "fieldName": "liBattTemp34",    "colDisplayName": "LiBattTemp34",     "title": "Battery Temperature 34", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "17", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage35": { "userIndex": 18, "fieldName": "liBattVoltage35", "colDisplayName": "LiBattVoltage 35", "title": "Battery Voltage 35",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "18", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent35": { "userIndex": 19, "fieldName": "liBattCurrent35", "colDisplayName": "LiBattCurrent 35", "title": "Battery Current 35",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "19", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC35":         { "userIndex": 20, "fieldName": "liSOC35",         "colDisplayName": "LiSOC35",          "title": "State of Charge 35",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "20", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH35":         { "userIndex": 21, "fieldName": "liSOH35",         "colDisplayName": "LiSOH35",          "title": "State of Health 35",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "21", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp35":    { "userIndex": 22, "fieldName": "liBattTemp35",    "colDisplayName": "LiBattTemp35",     "title": "Battery Temperature 35", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "22", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage36": { "userIndex": 23, "fieldName": "liBattVoltage36", "colDisplayName": "LiBattVoltage 36", "title": "Battery Voltage 36",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "23", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent36": { "userIndex": 24, "fieldName": "liBattCurrent36", "colDisplayName": "LiBattCurrent 36", "title": "Battery Current 36",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "24", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC36":         { "userIndex": 25, "fieldName": "liSOC36",         "colDisplayName": "LiSOC36",          "title": "State of Charge 36",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "25", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH36":         { "userIndex": 26, "fieldName": "liSOH36",         "colDisplayName": "LiSOH36",          "title": "State of Health 36",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "26", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp36":    { "userIndex": 27, "fieldName": "liBattTemp36",    "colDisplayName": "LiBattTemp36",     "title": "Battery Temperature 36", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "27", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage37": { "userIndex": 28, "fieldName": "liBattVoltage37", "colDisplayName": "LiBattVoltage 37", "title": "Battery Voltage 37",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "28", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent37": { "userIndex": 29, "fieldName": "liBattCurrent37", "colDisplayName": "LiBattCurrent 37", "title": "Battery Current 37",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "29", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC37":         { "userIndex": 30, "fieldName": "liSOC37",         "colDisplayName": "LiSOC37",          "title": "State of Charge 37",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "30", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH37":         { "userIndex": 31, "fieldName": "liSOH37",         "colDisplayName": "LiSOH37",          "title": "State of Health 37",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "31", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp37":    { "userIndex": 32, "fieldName": "liBattTemp37",    "colDisplayName": "LiBattTemp37",     "title": "Battery Temperature 37", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "32", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage38": { "userIndex": 33, "fieldName": "liBattVoltage38", "colDisplayName": "LiBattVoltage 38", "title": "Battery Voltage 38",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "33", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent38": { "userIndex": 34, "fieldName": "liBattCurrent38", "colDisplayName": "LiBattCurrent 38", "title": "Battery Current 38",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "34", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC38":         { "userIndex": 35, "fieldName": "liSOC38",         "colDisplayName": "LiSOC38",          "title": "State of Charge 38",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "35", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH38":         { "userIndex": 36, "fieldName": "liSOH38",         "colDisplayName": "LiSOH38",          "title": "State of Health 38",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "36", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp38":    { "userIndex": 37, "fieldName": "liBattTemp38",    "colDisplayName": "LiBattTemp38",     "title": "Battery Temperature 38", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "37", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage39": { "userIndex": 38, "fieldName": "liBattVoltage39", "colDisplayName": "LiBattVoltage 39", "title": "Battery Voltage 39",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "38", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent39": { "userIndex": 39, "fieldName": "liBattCurrent39", "colDisplayName": "LiBattCurrent 39", "title": "Battery Current 39",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "39", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC39":         { "userIndex": 40, "fieldName": "liSOC39",         "colDisplayName": "LiSOC39",          "title": "State of Charge 39",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "40", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH39":         { "userIndex": 41, "fieldName": "liSOH39",         "colDisplayName": "LiSOH39",          "title": "State of Health 39",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "41", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp39":    { "userIndex": 42, "fieldName": "liBattTemp39",    "colDisplayName": "LiBattTemp39",     "title": "Battery Temperature 39", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "42", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage40": { "userIndex": 43, "fieldName": "liBattVoltage40", "colDisplayName": "LiBattVoltage 40", "title": "Battery Voltage 40",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "43", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent40": { "userIndex": 44, "fieldName": "liBattCurrent40", "colDisplayName": "LiBattCurrent 40", "title": "Battery Current 40",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "44", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC40":         { "userIndex": 45, "fieldName": "liSOC40",         "colDisplayName": "LiSOC40",          "title": "State of Charge 40",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "45", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH40":         { "userIndex": 46, "fieldName": "liSOH40",         "colDisplayName": "LiSOH40",          "title": "State of Health 40",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "46", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp40":    { "userIndex": 47, "fieldName": "liBattTemp40",    "colDisplayName": "LiBattTemp40",     "title": "Battery Temperature 40", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "47", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage41": { "userIndex": 48, "fieldName": "liBattVoltage41", "colDisplayName": "LiBattVoltage 41", "title": "Battery Voltage 41",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "48", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent41": { "userIndex": 49, "fieldName": "liBattCurrent41", "colDisplayName": "LiBattCurrent 41", "title": "Battery Current 41",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "49", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC41":         { "userIndex": 50, "fieldName": "liSOC41",         "colDisplayName": "LiSOC41",          "title": "State of Charge 41",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "50", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH41":         { "userIndex": 51, "fieldName": "liSOH41",         "colDisplayName": "LiSOH41",          "title": "State of Health 41",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "51", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp41":    { "userIndex": 52, "fieldName": "liBattTemp41",    "colDisplayName": "LiBattTemp41",     "title": "Battery Temperature 41", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "52", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage42": { "userIndex": 53, "fieldName": "liBattVoltage42", "colDisplayName": "LiBattVoltage 42", "title": "Battery Voltage 42",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "53", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent42": { "userIndex": 54, "fieldName": "liBattCurrent42", "colDisplayName": "LiBattCurrent 42", "title": "Battery Current 42",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "54", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC42":         { "userIndex": 55, "fieldName": "liSOC42",         "colDisplayName": "LiSOC42",          "title": "State of Charge 42",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "55", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH42":         { "userIndex": 56, "fieldName": "liSOH42",         "colDisplayName": "LiSOH42",          "title": "State of Health 42",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "56", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp42":    { "userIndex": 57, "fieldName": "liBattTemp42",    "colDisplayName": "LiBattTemp42",     "title": "Battery Temperature 42", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "57", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage43": { "userIndex": 58, "fieldName": "liBattVoltage43", "colDisplayName": "LiBattVoltage 43", "title": "Battery Voltage 43",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "58", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent43": { "userIndex": 59, "fieldName": "liBattCurrent43", "colDisplayName": "LiBattCurrent 43", "title": "Battery Current 43",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "59", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC43":         { "userIndex": 60, "fieldName": "liSOC43",         "colDisplayName": "LiSOC43",          "title": "State of Charge 43",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "60", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH43":         { "userIndex": 61, "fieldName": "liSOH43",         "colDisplayName": "LiSOH43",          "title": "State of Health 43",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "61", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp43":    { "userIndex": 62, "fieldName": "liBattTemp43",    "colDisplayName": "LiBattTemp43",     "title": "Battery Temperature 43", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "62", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage44": { "userIndex": 63, "fieldName": "liBattVoltage44", "colDisplayName": "LiBattVoltage 44", "title": "Battery Voltage 44",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "63", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent44": { "userIndex": 64, "fieldName": "liBattCurrent44", "colDisplayName": "LiBattCurrent 44", "title": "Battery Current 44",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "64", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC44":         { "userIndex": 65, "fieldName": "liSOC44",         "colDisplayName": "LiSOC44",          "title": "State of Charge 44",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "65", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH44":         { "userIndex": 66, "fieldName": "liSOH44",         "colDisplayName": "LiSOH44",          "title": "State of Health 44",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "66", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp44":    { "userIndex": 67, "fieldName": "liBattTemp44",    "colDisplayName": "LiBattTemp44",     "title": "Battery Temperature 44", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "67", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage45": { "userIndex": 68, "fieldName": "liBattVoltage45", "colDisplayName": "LiBattVoltage 45", "title": "Battery Voltage 45",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "68", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent45": { "userIndex": 69, "fieldName": "liBattCurrent45", "colDisplayName": "LiBattCurrent 45", "title": "Battery Current 45",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "69", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC45":         { "userIndex": 70, "fieldName": "liSOC45",         "colDisplayName": "LiSOC45",          "title": "State of Charge 45",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "70", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH45":         { "userIndex": 71, "fieldName": "liSOH45",         "colDisplayName": "LiSOH45",          "title": "State of Health 45",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "71", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp45":    { "userIndex": 72, "fieldName": "liBattTemp45",    "colDisplayName": "LiBattTemp45",     "title": "Battery Temperature 45", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "72", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage46": { "userIndex": 73, "fieldName": "liBattVoltage46", "colDisplayName": "LiBattVoltage 46", "title": "Battery Voltage 46",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "73", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent46": { "userIndex": 74, "fieldName": "liBattCurrent46", "colDisplayName": "LiBattCurrent 46", "title": "Battery Current 46",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "74", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC46":         { "userIndex": 75, "fieldName": "liSOC46",         "colDisplayName": "LiSOC46",          "title": "State of Charge 46",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "75", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH46":         { "userIndex": 76, "fieldName": "liSOH46",         "colDisplayName": "LiSOH46",          "title": "State of Health 46",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "76", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp46":    { "userIndex": 77, "fieldName": "liBattTemp46",    "colDisplayName": "LiBattTemp46",     "title": "Battery Temperature 46", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "77", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage47": { "userIndex": 78, "fieldName": "liBattVoltage47", "colDisplayName": "LiBattVoltage 47", "title": "Battery Voltage 47",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "78", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent47": { "userIndex": 79, "fieldName": "liBattCurrent47", "colDisplayName": "LiBattCurrent 47", "title": "Battery Current 47",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "79", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC47":         { "userIndex": 80, "fieldName": "liSOC47",         "colDisplayName": "LiSOC47",          "title": "State of Charge 47",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "80", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH47":         { "userIndex": 81, "fieldName": "liSOH47",         "colDisplayName": "LiSOH47",          "title": "State of Health 47",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "81", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp47":    { "userIndex": 82, "fieldName": "liBattTemp47",    "colDisplayName": "LiBattTemp47",     "title": "Battery Temperature 47", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "82", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage48": { "userIndex": 83, "fieldName": "liBattVoltage48", "colDisplayName": "LiBattVoltage 48", "title": "Battery Voltage 48",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "83", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent48": { "userIndex": 84, "fieldName": "liBattCurrent48", "colDisplayName": "LiBattCurrent 48", "title": "Battery Current 48",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "84", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC48":         { "userIndex": 85, "fieldName": "liSOC48",         "colDisplayName": "LiSOC48",          "title": "State of Charge 48",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "85", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH48":         { "userIndex": 86, "fieldName": "liSOH48",         "colDisplayName": "LiSOH48",          "title": "State of Health 48",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "86", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp48":    { "userIndex": 87, "fieldName": "liBattTemp48",    "colDisplayName": "LiBattTemp48",     "title": "Battery Temperature 48", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "87", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false }
};
