export const LITHIUM_COLUMNS_49_TO_64 = {
  "smSitecode": {
    "userIndex": 0,
    "fieldName": "smSitecode",
    "colDisplayName": "Site Code",
    "title": "Site Code",
    "widthOfColumn": 150,
    "colType": "text",
    "dataType": "text",
    "id": "0",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": true,
    "isCustomAttributeColumn": false
  },
  "lastUpdated": {
    "userIndex": 1,
    "fieldName": "lastUpdated",
    "colDisplayName": "Last Updated",
    "title": "Last Updated",
    "widthOfColumn": 160,
    "colType": "text",
    "dataType": "text",
    "id": "1",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "clusterName": {
    "userIndex": 2,
    "fieldName": "clusterName",
    "colDisplayName": "Cluster Name",
    "title": "Cluster Name",
    "widthOfColumn": 150,
    "colType": "text",
    "dataType": "text",
    "id": "2",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": true,
    "isCustomAttributeColumn": false
  },
  "sitetypeid": {
    "userIndex": 3,
    "fieldName": "sitetypeid",
    "colDisplayName": "Site Type",
    "title": "Site Type",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "3",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "zone": {
    "userIndex": 4,
    "fieldName": "zone",
    "colDisplayName": "Zone",
    "title": "Zone",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "4",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "region": {
    "userIndex": 5,
    "fieldName": "region",
    "colDisplayName": "Region",
    "title": "Region",
    "widthOfColumn": 120,
    "colType": "text",
    "dataType": "text",
    "id": "5",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "powersource": {
    "userIndex": 6,
    "fieldName": "powersource",
    "colDisplayName": "Power Source",
    "title": "Power Source",
    "widthOfColumn": 140,
    "colType": "text",
    "dataType": "text",
    "id": "6",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "deviceType": {
    "userIndex": 7,
    "fieldName": "deviceType",
    "colDisplayName": "Device Type",
    "title": "Device Type",
    "widthOfColumn": 140,
    "colType": "text",
    "dataType": "text",
    "id": "7",
    "imgName": "",
    "tooltipSrc": "",
    "function": "",
    "funParams": "",
    "wrapData": "",
    "isSortSupported": false,
    "isCustomAttributeColumn": false
  },
  "liBattVoltage49": { "userIndex": 8,  "fieldName": "liBattVoltage49", "colDisplayName": "LiBattVoltage 49", "title": "Battery Voltage 49",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "8",  "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent49": { "userIndex": 9,  "fieldName": "liBattCurrent49", "colDisplayName": "LiBattCurrent 49", "title": "Battery Current 49",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "9",  "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC49":         { "userIndex": 10, "fieldName": "liSOC49",         "colDisplayName": "LiSOC49",          "title": "State of Charge 49",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "10", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH49":         { "userIndex": 11, "fieldName": "liSOH49",         "colDisplayName": "LiSOH49",          "title": "State of Health 49",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "11", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp49":    { "userIndex": 12, "fieldName": "liBattTemp49",    "colDisplayName": "LiBattTemp49",     "title": "Battery Temperature 49", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "12", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage50": { "userIndex": 13, "fieldName": "liBattVoltage50", "colDisplayName": "LiBattVoltage 50", "title": "Battery Voltage 50",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "13", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent50": { "userIndex": 14, "fieldName": "liBattCurrent50", "colDisplayName": "LiBattCurrent 50", "title": "Battery Current 50",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "14", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC50":         { "userIndex": 15, "fieldName": "liSOC50",         "colDisplayName": "LiSOC50",          "title": "State of Charge 50",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "15", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH50":         { "userIndex": 16, "fieldName": "liSOH50",         "colDisplayName": "LiSOH50",          "title": "State of Health 50",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "16", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp50":    { "userIndex": 17, "fieldName": "liBattTemp50",    "colDisplayName": "LiBattTemp50",     "title": "Battery Temperature 50", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "17", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage51": { "userIndex": 18, "fieldName": "liBattVoltage51", "colDisplayName": "LiBattVoltage 51", "title": "Battery Voltage 51",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "18", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent51": { "userIndex": 19, "fieldName": "liBattCurrent51", "colDisplayName": "LiBattCurrent 51", "title": "Battery Current 51",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "19", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC51":         { "userIndex": 20, "fieldName": "liSOC51",         "colDisplayName": "LiSOC51",          "title": "State of Charge 51",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "20", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH51":         { "userIndex": 21, "fieldName": "liSOH51",         "colDisplayName": "LiSOH51",          "title": "State of Health 51",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "21", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp51":    { "userIndex": 22, "fieldName": "liBattTemp51",    "colDisplayName": "LiBattTemp51",     "title": "Battery Temperature 51", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "22", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage52": { "userIndex": 23, "fieldName": "liBattVoltage52", "colDisplayName": "LiBattVoltage 52", "title": "Battery Voltage 52",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "23", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent52": { "userIndex": 24, "fieldName": "liBattCurrent52", "colDisplayName": "LiBattCurrent 52", "title": "Battery Current 52",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "24", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC52":         { "userIndex": 25, "fieldName": "liSOC52",         "colDisplayName": "LiSOC52",          "title": "State of Charge 52",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "25", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH52":         { "userIndex": 26, "fieldName": "liSOH52",         "colDisplayName": "LiSOH52",          "title": "State of Health 52",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "26", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp52":    { "userIndex": 27, "fieldName": "liBattTemp52",    "colDisplayName": "LiBattTemp52",     "title": "Battery Temperature 52", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "27", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage53": { "userIndex": 28, "fieldName": "liBattVoltage53", "colDisplayName": "LiBattVoltage 53", "title": "Battery Voltage 53",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "28", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent53": { "userIndex": 29, "fieldName": "liBattCurrent53", "colDisplayName": "LiBattCurrent 53", "title": "Battery Current 53",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "29", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC53":         { "userIndex": 30, "fieldName": "liSOC53",         "colDisplayName": "LiSOC53",          "title": "State of Charge 53",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "30", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH53":         { "userIndex": 31, "fieldName": "liSOH53",         "colDisplayName": "LiSOH53",          "title": "State of Health 53",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "31", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp53":    { "userIndex": 32, "fieldName": "liBattTemp53",    "colDisplayName": "LiBattTemp53",     "title": "Battery Temperature 53", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "32", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage54": { "userIndex": 33, "fieldName": "liBattVoltage54", "colDisplayName": "LiBattVoltage 54", "title": "Battery Voltage 54",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "33", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent54": { "userIndex": 34, "fieldName": "liBattCurrent54", "colDisplayName": "LiBattCurrent 54", "title": "Battery Current 54",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "34", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC54":         { "userIndex": 35, "fieldName": "liSOC54",         "colDisplayName": "LiSOC54",          "title": "State of Charge 54",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "35", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH54":         { "userIndex": 36, "fieldName": "liSOH54",         "colDisplayName": "LiSOH54",          "title": "State of Health 54",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "36", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp54":    { "userIndex": 37, "fieldName": "liBattTemp54",    "colDisplayName": "LiBattTemp54",     "title": "Battery Temperature 54", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "37", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage55": { "userIndex": 38, "fieldName": "liBattVoltage55", "colDisplayName": "LiBattVoltage 55", "title": "Battery Voltage 55",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "38", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent55": { "userIndex": 39, "fieldName": "liBattCurrent55", "colDisplayName": "LiBattCurrent 55", "title": "Battery Current 55",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "39", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC55":         { "userIndex": 40, "fieldName": "liSOC55",         "colDisplayName": "LiSOC55",          "title": "State of Charge 55",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "40", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH55":         { "userIndex": 41, "fieldName": "liSOH55",         "colDisplayName": "LiSOH55",          "title": "State of Health 55",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "41", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp55":    { "userIndex": 42, "fieldName": "liBattTemp55",    "colDisplayName": "LiBattTemp55",     "title": "Battery Temperature 55", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "42", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage56": { "userIndex": 43, "fieldName": "liBattVoltage56", "colDisplayName": "LiBattVoltage 56", "title": "Battery Voltage 56",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "43", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent56": { "userIndex": 44, "fieldName": "liBattCurrent56", "colDisplayName": "LiBattCurrent 56", "title": "Battery Current 56",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "44", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC56":         { "userIndex": 45, "fieldName": "liSOC56",         "colDisplayName": "LiSOC56",          "title": "State of Charge 56",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "45", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH56":         { "userIndex": 46, "fieldName": "liSOH56",         "colDisplayName": "LiSOH56",          "title": "State of Health 56",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "46", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp56":    { "userIndex": 47, "fieldName": "liBattTemp56",    "colDisplayName": "LiBattTemp56",     "title": "Battery Temperature 56", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "47", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage57": { "userIndex": 48, "fieldName": "liBattVoltage57", "colDisplayName": "LiBattVoltage 57", "title": "Battery Voltage 57",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "48", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent57": { "userIndex": 49, "fieldName": "liBattCurrent57", "colDisplayName": "LiBattCurrent 57", "title": "Battery Current 57",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "49", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC57":         { "userIndex": 50, "fieldName": "liSOC57",         "colDisplayName": "LiSOC57",          "title": "State of Charge 57",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "50", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH57":         { "userIndex": 51, "fieldName": "liSOH57",         "colDisplayName": "LiSOH57",          "title": "State of Health 57",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "51", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp57":    { "userIndex": 52, "fieldName": "liBattTemp57",    "colDisplayName": "LiBattTemp57",     "title": "Battery Temperature 57", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "52", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage58": { "userIndex": 53, "fieldName": "liBattVoltage58", "colDisplayName": "LiBattVoltage 58", "title": "Battery Voltage 58",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "53", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent58": { "userIndex": 54, "fieldName": "liBattCurrent58", "colDisplayName": "LiBattCurrent 58", "title": "Battery Current 58",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "54", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC58":         { "userIndex": 55, "fieldName": "liSOC58",         "colDisplayName": "LiSOC58",          "title": "State of Charge 58",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "55", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH58":         { "userIndex": 56, "fieldName": "liSOH58",         "colDisplayName": "LiSOH58",          "title": "State of Health 58",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "56", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp58":    { "userIndex": 57, "fieldName": "liBattTemp58",    "colDisplayName": "LiBattTemp58",     "title": "Battery Temperature 58", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "57", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage59": { "userIndex": 58, "fieldName": "liBattVoltage59", "colDisplayName": "LiBattVoltage 59", "title": "Battery Voltage 59",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "58", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent59": { "userIndex": 59, "fieldName": "liBattCurrent59", "colDisplayName": "LiBattCurrent 59", "title": "Battery Current 59",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "59", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC59":         { "userIndex": 60, "fieldName": "liSOC59",         "colDisplayName": "LiSOC59",          "title": "State of Charge 59",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "60", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH59":         { "userIndex": 61, "fieldName": "liSOH59",         "colDisplayName": "LiSOH59",          "title": "State of Health 59",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "61", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp59":    { "userIndex": 62, "fieldName": "liBattTemp59",    "colDisplayName": "LiBattTemp59",     "title": "Battery Temperature 59", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "62", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage60": { "userIndex": 63, "fieldName": "liBattVoltage60", "colDisplayName": "LiBattVoltage 60", "title": "Battery Voltage 60",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "63", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent60": { "userIndex": 64, "fieldName": "liBattCurrent60", "colDisplayName": "LiBattCurrent 60", "title": "Battery Current 60",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "64", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC60":         { "userIndex": 65, "fieldName": "liSOC60",         "colDisplayName": "LiSOC60",          "title": "State of Charge 60",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "65", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH60":         { "userIndex": 66, "fieldName": "liSOH60",         "colDisplayName": "LiSOH60",          "title": "State of Health 60",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "66", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp60":    { "userIndex": 67, "fieldName": "liBattTemp60",    "colDisplayName": "LiBattTemp60",     "title": "Battery Temperature 60", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "67", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage61": { "userIndex": 68, "fieldName": "liBattVoltage61", "colDisplayName": "LiBattVoltage 61", "title": "Battery Voltage 61",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "68", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent61": { "userIndex": 69, "fieldName": "liBattCurrent61", "colDisplayName": "LiBattCurrent 61", "title": "Battery Current 61",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "69", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC61":         { "userIndex": 70, "fieldName": "liSOC61",         "colDisplayName": "LiSOC61",          "title": "State of Charge 61",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "70", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH61":         { "userIndex": 71, "fieldName": "liSOH61",         "colDisplayName": "LiSOH61",          "title": "State of Health 61",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "71", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp61":    { "userIndex": 72, "fieldName": "liBattTemp61",    "colDisplayName": "LiBattTemp61",     "title": "Battery Temperature 61", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "72", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage62": { "userIndex": 73, "fieldName": "liBattVoltage62", "colDisplayName": "LiBattVoltage 62", "title": "Battery Voltage 62",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "73", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent62": { "userIndex": 74, "fieldName": "liBattCurrent62", "colDisplayName": "LiBattCurrent 62", "title": "Battery Current 62",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "74", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC62":         { "userIndex": 75, "fieldName": "liSOC62",         "colDisplayName": "LiSOC62",          "title": "State of Charge 62",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "75", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH62":         { "userIndex": 76, "fieldName": "liSOH62",         "colDisplayName": "LiSOH62",          "title": "State of Health 62",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "76", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp62":    { "userIndex": 77, "fieldName": "liBattTemp62",    "colDisplayName": "LiBattTemp62",     "title": "Battery Temperature 62", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "77", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage63": { "userIndex": 78, "fieldName": "liBattVoltage63", "colDisplayName": "LiBattVoltage 63", "title": "Battery Voltage 63",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "78", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent63": { "userIndex": 79, "fieldName": "liBattCurrent63", "colDisplayName": "LiBattCurrent 63", "title": "Battery Current 63",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "79", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC63":         { "userIndex": 80, "fieldName": "liSOC63",         "colDisplayName": "LiSOC63",          "title": "State of Charge 63",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "80", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH63":         { "userIndex": 81, "fieldName": "liSOH63",         "colDisplayName": "LiSOH63",          "title": "State of Health 63",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "81", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp63":    { "userIndex": 82, "fieldName": "liBattTemp63",    "colDisplayName": "LiBattTemp63",     "title": "Battery Temperature 63", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "82", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },

  "liBattVoltage64": { "userIndex": 83, "fieldName": "liBattVoltage64", "colDisplayName": "LiBattVoltage 64", "title": "Battery Voltage 64",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "83", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattCurrent64": { "userIndex": 84, "fieldName": "liBattCurrent64", "colDisplayName": "LiBattCurrent 64", "title": "Battery Current 64",    "widthOfColumn": 130, "colType": "text", "dataType": "text", "id": "84", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOC64":         { "userIndex": 85, "fieldName": "liSOC64",         "colDisplayName": "LiSOC64",          "title": "State of Charge 64",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "85", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liSOH64":         { "userIndex": 86, "fieldName": "liSOH64",         "colDisplayName": "LiSOH64",          "title": "State of Health 64",     "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "86", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false },
  "liBattTemp64":    { "userIndex": 87, "fieldName": "liBattTemp64",    "colDisplayName": "LiBattTemp64",     "title": "Battery Temperature 64", "widthOfColumn": 120, "colType": "text", "dataType": "text", "id": "87", "imgName": "", "tooltipSrc": "", "function": "", "funParams": "", "wrapData": "", "isSortSupported": false, "isCustomAttributeColumn": false }
};
