
export const OUTAGE_CATEGORY_COLUMN_HEADER = {
  srno: {
    userIndex: 0,
    fieldName: 'srno',
    colDisplayName: 'SrNo',
    title: 'SrNo',
    widthOfColumn: 50,
    colType: 'text',
    dataType: 'text',
    id: '0',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  outageCategory: {
    userIndex: 1,
    fieldName: 'outageCategory',
    colDisplayName: 'Outage Category Name',
    title: 'Outage Category Name',
    widthOfColumn: 250,
    colType: 'textwithlink',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: 'openOutageCategoryDataForEdit',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  delete: {
    id: '2',
    fieldName: 'delete',
    colDisplayName: 'Action',
    colType: 'textwithlink',
    dataType: 'text',
    userIndex: 2,
    imgName: '',
    tooltipSrc: '',
    function: 'openOutageCategoryForDelete',
    funParams: '',
    wrapData: '',
    widthOfColumn: 75,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
};
