
export const TOWER_STATUS_COLUMN_HEADER: any = {
  checkbox: {
    id: '0',
    fieldName: 'smSiteCode',
    colDisplayName: '',
    colType: 'checkbox',
    userIndex: -1,
    imgName: '',
    tooltipSrc: '',
    dataType: 'checkbox',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 35,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  lastUpdated: {
    userIndex: 1,
    fieldName: 'lastUpdated',
    colDisplayName: 'Last Updated',
    title: 'Last Updated',
    widthOfColumn: 175,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smSiteCode: {
    userIndex: 2,
    fieldName: 'smSiteCode',
    colDisplayName: 'Site Id',
    title: 'Site Id',
    widthOfColumn: 125,
    colType: 'textwithlink',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: 'viewSiteDetails',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  siteName: {
    userIndex: 3,
    fieldName: 'siteName',
    colDisplayName: 'Site Name',
    title: 'Site Name',
    widthOfColumn: 175,
    colType: 'textwithlink',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: 'loadSiteDetails',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  powerSource: {
    userIndex: 4,
    fieldName: 'powerSource',
    colDisplayName: 'Power Source',
    title: 'Power Source',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  customerName: {
    userIndex: 5,
    fieldName: 'customerName',
    colDisplayName: 'Customer',
    title: 'Customer',
    widthOfColumn: 125,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  engineerName: {
    userIndex: 6,
    fieldName: 'engineerName',
    colDisplayName: 'Engineer Name',
    title: 'Engineer Name',
    widthOfColumn: 125,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '17',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  batterySOC: {
    userIndex: 7,
    fieldName: 'batterySOC',
    colDisplayName: 'Battery SOC',
    title: 'Battery SOC',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dgBatteryVoltage: {
    userIndex: 8,
    fieldName: 'dgBatteryVoltage',
    colDisplayName: 'DG Battery Voltage',
    title: 'DG Battery Voltage',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dcLoad: {
    userIndex: 9,
    fieldName: 'dcLoad',
    colDisplayName: 'DC Load',
    title: 'DC Load',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dcVoltage: {
    userIndex: 10,
    fieldName: 'dcVoltage',
    colDisplayName: 'DC Voltage',
    title: 'DC Voltage',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dgPower: {
    userIndex: 11,
    fieldName: 'dgPower',
    colDisplayName: 'DG Power (Kw)',
    title: 'DG Power (KW)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  fuelLevel: {
    userIndex: 12,
    fieldName: 'fuelLevel',
    colDisplayName: 'Fuel Level',
    title: 'Fuel Level (Ltrs.)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  solarKw: {
    userIndex: 13,
    fieldName: 'solarKw',
    colDisplayName: 'Solar Kw',
    title: 'Solar (KW)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  totalac: {
    userIndex: 14,
    fieldName: 'totalac',
    colDisplayName: 'Total Ac',
    title: 'Total (Ac)',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '14',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  critical: {
    userIndex: 15,
    fieldName: 'critical',
    colDisplayName: 'Critical',
    title: 'Critical',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '15',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  major: {
    userIndex: 16,
    fieldName: 'major',
    colDisplayName: 'Major',
    title: 'Major',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '16',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  minor: {
    userIndex: 17,
    fieldName: 'minor',
    colDisplayName: 'Minor',
    title: 'Minor',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '17',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  age: {
    userIndex: 18,
    fieldName: 'age',
    colDisplayName: 'Offline Duration',
    title: 'Offline Duration',
    widthOfColumn: 100,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '18',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  location: {
    userIndex: 19,
    fieldName: 'location',
    colDisplayName: 'Location',
    title: 'Location',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '19',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  alarmCategory: {
    userIndex: 20,
    fieldName: 'alarmCategory',
    colDisplayName: 'Alarm Category',
    title: 'Alarm Category',
    widthOfColumn: 125,
    colType: 'textwithlink',
    dataType: 'text',
    id: '20',
    imgName: '',
    tooltipSrc: '',
    function: 'viewAlarmCategory',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  hourlyReport: {
    userIndex: 21,
    fieldName: 'hourlyReport',
    colDisplayName: 'Hourly Report',
    title: 'Hourly Report',
    widthOfColumn: 125,
    colType: 'textwithlink',
    dataType: 'text',
    id: '21',
    imgName: '',
    tooltipSrc: '',
    function: 'viewHourlyReport',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  imgPath: {
    userIndex: 22,
    fieldName: 'imgPath',
    colDisplayName: 'Image',
    title: 'Image',
    widthOfColumn: 125,
    colType: 'textwithlink',
    dataType: 'text',
    id: '22',
    imgName: '',
    tooltipSrc: '',
    function: 'viewImagePath',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
};
