export const TOWER_STATUS_COLUMN_HEADER = {
  lastUpdated: {
    userIndex: 0,
    fieldName: 'lastUpdated',
    colDisplayName: 'Last Updated',
    title: 'Last Updated',
    widthOfColumn: 175,
    colType: 'text',
    dataType: 'date',
    id: '0',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: true,
    order: 'asc',
    isCustomAttributeColumn: false
  },
  smSiteCode: {
    userIndex: 1,
    fieldName: 'smSiteCode',
    colDisplayName: 'Site Id',
    title: 'Site Id',
    widthOfColumn: 125,
    colType: 'textwithlink',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: 'viewSiteDetails',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  siteName: {
    userIndex: 2,
    fieldName: 'siteName',
    colDisplayName: 'Site Name',
    title: 'Site Name',
    widthOfColumn: 175,
    colType: 'textwithlink',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: 'loadSiteDetails',
    funParams: '',
    wrapData: '',
    order: 'asc',
    isSortSupported: true,
    isCustomAttributeColumn: false
  },
  powerSource: {
    userIndex: 3,
    fieldName: 'powerSource',
    colDisplayName: 'Power Source',
    title: 'Power Source',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    order: 'asc',
    isSortSupported: true,
    isCustomAttributeColumn: false
  },
  customerName: {
    userIndex: 4,
    fieldName: 'customerName',
    colDisplayName: 'Customer',
    title: 'Customer',
    widthOfColumn: 125,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dcVoltage: {
    userIndex: 5,
    fieldName: 'dcVoltage',
    colDisplayName: 'DC Voltage (V)	',
    title: 'DC Voltage (V)	',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'number',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    order: 'asc',
    isSortSupported: true,
    isCustomAttributeColumn: false
  },
  batterySOC: {
    userIndex: 6,
    fieldName: 'batterySOC',
    colDisplayName: 'Battery SOC',
    title: 'Battery SOC',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dcLoad: {
    userIndex: 7,
    fieldName: 'dcLoad',
    colDisplayName: 'DC Load 	',
    title: 'DC Load 	',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dgBatteryVoltage: {
    userIndex: 8,
    fieldName: 'dgBatteryVoltage',
    colDisplayName: 'DG Start Voltage',
    title: 'DG Start Voltage',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },

  dgStartSOC: {
    userIndex: 9,
    fieldName: 'dgStartSOC',
    colDisplayName: 'DG Start SOC',
    title: 'DG Start SOC',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
 
  solarKw: {
    userIndex: 10,
    fieldName: 'solarKw',
    colDisplayName: 'Solar (kW)	',
    title: 'Solar (kW)',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dgPower: {
    userIndex: 11,
    fieldName: 'dgPower',
    colDisplayName: 'DG Power (Kw)',
    title: 'DG Power (KW)',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  batteryLifeCycleCount: {
    userIndex: 12,
    fieldName: 'batteryLifeCycleCount',
    colDisplayName: 'Battery Life Cycle Count',
    title: 'Battery Life Cycle Count',
    widthOfColumn: 170,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  fuelLevel: {
    userIndex: 13,
    fieldName: 'fuelLevel',
    colDisplayName: 'Fuel Liters',
    title: 'Fuel Liters',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  totalac: {
    userIndex: 14,
    fieldName: 'totalac',
    colDisplayName: 'Total AC (kW)	',
    title: 'Total AC (kW)	',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '14',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  ambAirTemp: {
    userIndex: 15,
    fieldName: 'ambAirTemp',
    colDisplayName: 'Amb Air Temp °C (WS)',
    title: 'Amb Air Temp °C (WS)',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '15',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  globalIrradiance: {
    userIndex: 15.1,
    fieldName: 'globalIrradiance',
    colDisplayName: 'Global Irradiance W/m2(WS)',
    title: 'Global Irradiance W/m2(WS)',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '16',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  pvUpperSideTemp: {
    userIndex: 16,
    fieldName: 'pvUpperSideTemp',
    colDisplayName: 'PV Upper Side Temp*C(WS)',
    title: 'PV Upper Side Temp*C(WS)',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '16',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  pvLowerSideTemp: {
    userIndex: 17,
    fieldName: 'pvLowerSideTemp',
    colDisplayName: 'PV Lower Side Temp*C(WS)',
    title: 'PV Lower Side Temp*C(WS)',
    widthOfColumn: 200,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '17',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  engineerName: {
    userIndex: 18,
    fieldName: 'engineerName',
    colDisplayName: 'Engineer Name',
    title: 'Engineer Name',
    widthOfColumn: 125,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '18',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  critical: {
    userIndex: 19,
    fieldName: 'critical',
    colDisplayName: 'Critical',
    title: 'Critical',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '19',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  major: {
    userIndex: 20,
    fieldName: 'major',
    colDisplayName: 'Major',
    title: 'Major',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '20',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  minor: {
    userIndex: 21,
    fieldName: 'minor',
    colDisplayName: 'Minor',
    title: 'Minor',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '22',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  age: {
    userIndex: 23,
    fieldName: 'age',
    colDisplayName: 'Offline Duration',
    title: 'Offline Duration',
    widthOfColumn: 150,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '23',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  location: {
    userIndex: 24,
    fieldName: 'location',
    colDisplayName: 'Location',
    title: 'Location',
    widthOfColumn: 670,
    colType: 'text',
    isAvailTooltip: true,
    dataType: 'text',
    id: '24',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  alarmCategory: {
    userIndex: 25,
    fieldName: 'alarmCategory',
    colDisplayName: 'Alarm Category',
    title: 'Alarm Category',
    widthOfColumn: 125,
    colType: 'textwithlink',
    dataType: 'text',
    id: '25',
    imgName: '',
    tooltipSrc: '',
    function: 'viewAlarmCategory',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  hourlyReport: {
    userIndex: 26,
    fieldName: 'hourlyReport',
    colDisplayName: 'Hourly Report',
    title: 'Hourly Report',
    widthOfColumn: 125,
    colType: 'textwithlink',
    dataType: 'text',
    id: '26',
    imgName: '',
    tooltipSrc: '',
    function: 'viewHourlyReport',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  imgPath: {
    userIndex: 27,
    fieldName: 'imgPath',
    colDisplayName: 'Image',
    title: 'Image',
    widthOfColumn: 125,
    colType: 'textwithlink',
    dataType: 'text',
    id: '27',
    imgName: '',
    tooltipSrc: '',
    function: 'viewImagePath',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
};
