name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
      - production

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push TEST image (main)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/bitrms-frontend:test .
          docker push ${{ secrets.DOCKER_USERNAME }}/bitrms-frontend:test

      - name: Build and Push PROD image (production)
        if: github.ref == 'refs/heads/production'
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/bitrms-frontend:prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/bitrms-frontend:prod

      - name: Deploy to TEST server (main)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST_TEST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/bitrms-frontend:test
            docker stop bitrms-frontend || true
            docker rm bitrms-frontend || true
            docker run -d --name bitrms-frontend --restart always -p 4200:4200 -v /home/ubuntu/default.conf:/etc/nginx/conf.d/default.conf ${{ secrets.DOCKER_USERNAME }}/bitrms-frontend:test

  deploy-production:
    if: github.ref == 'refs/heads/production'
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy PROD image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/bitrms-frontend:prod
          docker stop bitrms-frontend || true
          docker rm bitrms-frontend || true
          docker run -d --name bitrms-frontend --restart always -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/bitrms-frontend:prod

  deploy-test:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy TEST image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/bitrms-frontend:test
          docker stop bitrms-frontend || true
          docker rm bitrms-frontend || true
          docker run -d --name bitrms-frontend --restart always -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/bitrms-frontend:test
