
export const REMOTE_COMMANDS_COLUMN_HEADER = {
  srno: {
    userIndex: 0,
    fieldName: 'srno',
    colDisplayName: 'SrNo',
    title: 'SrNo',
    widthOfColumn: 50,
    colType: 'text',
    dataType: 'text',
    id: '0',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  rmcTimestamp: {
    userIndex: 1,
    fieldName: 'rmcTimestamp',
    colDisplayName: 'Last Updated',
    title: 'Last Updated',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smSitecode: {
    userIndex: 2,
    fieldName: 'smSitecode',
    colDisplayName: 'Site Id',
    title: 'Site Id',
    widthOfColumn: 150,
    colType: 'textwithlink',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: 'openRemoteSiteCommands',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  forcedgstart: {
    userIndex: 3,
    fieldName: 'forcedgstart',
    colDisplayName: 'Force DG Start',
    title: 'Force DG Start',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  forcedgruntime: {
    userIndex: 4,
    fieldName: 'forcedgruntime',
    colDisplayName: 'Force DG Runtime',
    title: 'Force DG Runtime',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dgbatteryvoltage: {
    userIndex: 5,
    fieldName: 'dgbatteryvoltage',
    colDisplayName: 'DG Start Battery Voltage',
    title: 'DG Start Battery Voltage',
    widthOfColumn: 200,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  bulkvoltage: {
    userIndex: 6,
    fieldName: 'bulkvoltage',
    colDisplayName: 'Bulk Voltage',
    title: 'Bulk Voltage',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  floatvoltage: {
    userIndex: 7,
    fieldName: 'floatvoltage',
    colDisplayName: 'Float Voltage',
    title: 'Float Voltage',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  accharger_startvoltage: {
    userIndex: 8,
    fieldName: 'accharger_startvoltage',
    colDisplayName: 'AC Charger Start Voltage',
    title: 'AC Charger Start Voltage',
    widthOfColumn: 250,
    colType: 'text',
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  accharger_stopvoltage: {
    userIndex: 9,
    fieldName: 'accharger_stopvoltage',
    colDisplayName: 'AC Charger Stop Voltage',
    title: 'AC Charger Stop Voltage',
    widthOfColumn: 250,
    colType: 'text',
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  charger_batt_currentlimit: {
    userIndex: 10,
    fieldName: 'charger_batt_currentlimit',
    colDisplayName: 'Charger Battery Current Unit',
    title: 'Charger Battery Current Unit',
    widthOfColumn: 250,
    colType: 'text',
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  min_load_threshold_watt: {
    userIndex: 11,
    fieldName: 'min_load_threshold_watt',
    colDisplayName: 'Min Load Threshold Watt',
    title: 'Min Load Threshold Watt',
    widthOfColumn: 250,
    colType: 'text',
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  max_export_power_watt: {
    userIndex: 12,
    fieldName: 'max_export_power_watt',
    colDisplayName: 'Max Export Power Watt',
    title: 'Max Export Power Watt',
    widthOfColumn: 250,
    colType: 'text',
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  batt_capacity_kwh: {
    userIndex: 13,
    fieldName: 'batt_capacity_kwh',
    colDisplayName: 'Battery Capacity KWH',
    title: 'Battery Capacity KWH',
    widthOfColumn: 250,
    colType: 'text',
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
