
export const REMOTE_COMMANDS_COLUMN_HEADER = {
  srno: {
    userIndex: 0,
    fieldName: 'srno',
    colDisplayName: 'SrNo',
    title: 'SrNo',
    widthOfColumn: 50,
    colType: 'text',
    dataType: 'text',
    id: '0',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  lastUpdated: {
    userIndex: 1,
    fieldName: 'lastUpdated',
    colDisplayName: 'Last Updated',
    title: 'Last Updated',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  smSiteCode: {
    userIndex: 2,
    fieldName: 'smSiteCode',
    colDisplayName: 'Site Id',
    title: 'Site Id',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  forgeDgStart: {
    userIndex: 3,
    fieldName: 'forgeDgStart',
    colDisplayName: 'Forge DG Start',
    title: 'Forge DG Start',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  forgeDgRuntime: {
    userIndex: 4,
    fieldName: 'forgeDgRuntime',
    colDisplayName: 'Forge DG Runtime',
    title: 'Forge DG Runtime',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dgBatteryVoltage: {
    userIndex: 5,
    fieldName: 'dgBatteryVoltage',
    colDisplayName: 'DG Battery Voltage',
    title: 'DG Battery Voltage',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  bulkVoltage: {
    userIndex: 6,
    fieldName: 'bulkVoltage',
    colDisplayName: 'Bulk Voltage',
    title: 'Bulk Voltage',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  floatVoltage: {
    userIndex: 7,
    fieldName: 'faultVoltage',
    colDisplayName: 'Fault Voltage',
    title: 'Fault Voltage',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  acChargerStartVoltage: {
    userIndex: 8,
    fieldName: 'acChargerStartVoltage',
    colDisplayName: 'AC Charger Start Voltage',
    title: 'AC Charger Start Voltage',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  acChargerStopVoltage: {
    userIndex: 9,
    fieldName: 'acChargerStopVoltage',
    colDisplayName: 'AC Charger Stop Voltage',
    title: 'AC Charger Stop Voltage',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  chargerBatteryCurrentUnit: {
    userIndex: 10,
    fieldName: 'chargerBatteryCurrentUnit',
    colDisplayName: 'Charger Battery Current Unit',
    title: 'Charger Battery Current Unit',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  minLoadThresholdWatt: {
    userIndex: 11,
    fieldName: 'minLoadThresholdWatt',
    colDisplayName: 'Min Load Threshold Watt',
    title: 'Min Load Threshold Watt',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  maxExportPowerWatt: {
    userIndex: 12,
    fieldName: 'maxExportPowerWatt',
    colDisplayName: 'Max Export Power Watt',
    title: 'Max Export Power Watt',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  batteryCapacityKWH: {
    userIndex: 13,
    fieldName: 'batteryCapacityKWH',
    colDisplayName: 'Battery Capacity KWH',
    title: 'Battery Capacity KWH',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
